### ISSUE TITLE
Comfyui manager always reports an error when starting

### ISSUE THREAD

**Issue by tzhnihao** [Comfy-Org/ComfyUI-Manager#1099]
Hello, I always report this error in the background when comfyui starts up. It feels like a network problem, but it can start and run the workflow normally. It's just that these errors are reported every time it starts up. I tried to lower the version, but it doesn't report errors in very low versions, but it doesn't work well with the latest version of comfyui.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
Scenedetect.available False
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "E:\ComfyUI-aki-v1.3\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1354, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "E:\ComfyUI-aki-v1.3\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\ComfyUI-aki-v1.3\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1351, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1338, in get_cache
    json_obj = await core.get_data(uri, True)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 620, in get_data
    async with session.get(uri) as resp:
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
FishSpeech.available

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting

Try `bypass_ssl = True` 
If it doesn't work, you have to use a VPN.

**Comment by tzhnihao** [comment]
> https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting
> 
> Try `bypass_ssl = True`尝试 `bypass_ssl = 真` If it doesn't work, you have to use a VPN.如果它不起作用，您必须使用 VPN。

  Still reporting an error, but thanks for your help.

**Comment by coddz** [comment]
Me too.

Still reporting an error after adding bypass_ssl = True in config.ini


thanks for your help.

**Comment by coddz** [comment]
oh, the error is: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Exception in thread Thread-9 (<lambda>):
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "F:\ComfyUI-aki-v1.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1354, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "F:\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "F:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1351, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1338, in get_cache
    json_obj = await core.get_data(uri, True)
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 627, in get_data
    json_obj = json.loads(json_text)
  File "F:\ComfyUI-aki-v1.4\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "F:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by coddz** [comment]
the error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" is resolved through vpn. thanks your history issue reply "json.decoder.JSONDecodeError #1007"

**Comment by tzhnihao** [comment]
> Me too.
> 
> Still reporting an error after adding bypass_ssl = True in config.ini
> 
> thanks for your help.

那天我在逛作者的首页时，无意中看到：When you run the scan.sh script:

It updates the extension-node-map.json.

To do this, it pulls or clones the custom nodes listed in custom-node-list.json into ~/.tmp/default.
To skip this step, add the --skip-update option.......
于是我就试了下：The --skip-all option 添加到了scan.sh文件中，就不报错了。
既然你也报这个错，我猜你可能看的懂中文，就不翻译了。

**Comment by ltdrdata** [comment]
`scan.sh` is not created for the purpose of being used by end-users.
You should not use them.

**Comment by t00350320** [comment]
```
[2024-11-05 19:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-11-05 19:55] Exception in thread Thread-2 (<lambda>):
[2024-11-05 19:55] Traceback (most recent call last):
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
[2024-11-05 19:55]     return await self._loop.create_connection(*args, **kwargs)
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
[2024-11-05 19:55]     raise exceptions[0]
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
[2024-11-05 19:55]     sock = await self._connect_sock(
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
[2024-11-05 19:55]     await self.sock_connect(sock, address)
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
[2024-11-05 19:55]     return await fut
[2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
[2024-11-05 19:55]     raise OSError(err, f'Connect call failed {address}')
[2024-11-05 19:55] TimeoutError: [Errno 110] Connect call failed ('185.199.111.133', 443)
```
hi @ltdrdata  how to close or cancel this connetion request for Comfyui-Manager because my server in a Intranet while can't connect the Extranet？
thank you very much

**Comment by ltdrdata** [comment]
> ```
> [2024-11-05 19:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [2024-11-05 19:55] Exception in thread Thread-2 (<lambda>):
> [2024-11-05 19:55] Traceback (most recent call last):
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
> [2024-11-05 19:55]     return await self._loop.create_connection(*args, **kwargs)
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
> [2024-11-05 19:55]     raise exceptions[0]
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
> [2024-11-05 19:55]     sock = await self._connect_sock(
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
> [2024-11-05 19:55]     await self.sock_connect(sock, address)
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
> [2024-11-05 19:55]     return await fut
> [2024-11-05 19:55]   File "/usr/local/python3/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
> [2024-11-05 19:55]     raise OSError(err, f'Connect call failed {address}')
> [2024-11-05 19:55] TimeoutError: [Errno 110] Connect call failed ('185.199.111.133', 443)
> ```
> 
> hi @ltdrdata how to close or cancel this connetion request for Comfyui-Manager because my server in a Intranet while can't connect the Extranet？ thank you very much

Upload this request to here:
https://github.com/Comfy-Org/manager-core/issues

I'll patch it later.
