### ISSUE TITLE
Prestartup script error

### ISSUE THREAD

**Issue by diaopal** [Comfy-Org/ComfyUI-Manager#1170]
```
[START] Security scan
Using Python 3.11.9 environment at /Users/diaopal/src/.venv
Failed to execute startup-script: /Users/diaopal/src/ComfyUI/custom_nodes/ComfyUI-Manager/prestartup_script.py / list index out of range

Prestartup times for custom nodes:
   0.1 seconds (PRESTARTUP FAILED): /Users/diaopal/src/ComfyUI/custom_nodes/ComfyUI-Manager
```

After investigating and running `python prestartup_script.py`, I get:
```
[START] Security scan
Using Python 3.11.9 environment at /Users/diaopal/src/.venv
Traceback (most recent call last):
  File "/Users/diaopal/src/ComfyUI/custom_nodes/ComfyUI-Manager/prestartup_script.py", line 21, in <module>
    security_check.security_check()
  File "/Users/diaopal/src/ComfyUI/custom_nodes/ComfyUI-Manager/glob/security_check.py", line 49, in security_check
    anthropic_reqs = [x for x in anthropic_info.split('\n') if x.startswith("Requires")][0].split(': ')[1]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I suggest making the following change to the file below which fixes the issue: https://github.com/ltdrdata/ComfyUI-Manager/blob/ade30470ccbf09308e66351b46e663725f479508/glob/security_check.py#L56

```diff
+    except Exception:
-    except subprocess.CalledProcessError:
```

**Comment by ltdrdata** [comment]
Show me the value of `anthropic_info`.

```
print(f"anthropic_info: '{anthropic_info}')
```

**Comment by diaopal** [comment]
```
anthropic_info: 'Command '['uv', 'pip', 'show', 'anthropic']' returned non-zero exit status 1.
'
```

```shell
diaopal@diaopal-MacBook-Pro ~/s/ComfyUI (master)> uv pip show anthropic
Using Python 3.11.9 environment at /Users/diaopal/src/.venv
warning: Package(s) not found for: anthropic
```

<br>

Btw, `uv` doesn't have a pip module so I made one myself at `/Users/diaopal/src/.venv/lib/python3.11/site-packages/pip/__main__.py`:
```python
#!/usr/bin/env python3

# Wrapper for uv pip
# Execute with
# $ python3 -m pip

import sys, subprocess

if __package__ is None and not getattr(sys, 'frozen', False):
    # direct call of __main__.py
    import os.path
    path = os.path.realpath(os.path.abspath(__file__))
    sys.path.insert(0, os.path.dirname(os.path.dirname(path)))

if __name__ == '__main__':
    ls=['uv', 'pip'] + sys.argv.copy()
    try:
        subprocess.check_call(ls)
    except Exception as e:
        print(e)
```

So when `python -m pip` gets called, `uv pip` is called.

**Comment by ltdrdata** [comment]
In my opinion, it seems appropriate to have the wrapper correctly return the exit code.

**Comment by diaopal** [comment]
Oh you're right! I removed the try/except block and left the `subprocess.check_call(ls)` and now it works. Thank you!
