### ISSUE TITLE
after install comfyui-manager, it fails to start comyfui

### ISSUE THREAD

**Issue by Nomination-NRB** [Comfy-Org/ComfyUI-Manager#1183]
Hello, I meet this error when comfyui starts up. But it can start and run the workflow normally if I delete comfyui manager. I tried to find the solution in issues, but it doesn't work after I tried all the method I have found.

```bash
(comfyui) hx@hx:~/ComfyUI$ python main.py --listen 192.168.2.105 --port 7862
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-23 17:34:46.712772
** Platform: Linux
** Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
** Python executable: /home/hx/anaconda3/envs/comfyui/bin/python
** ComfyUI Path: /home/hx/ComfyUI
** Log path: /home/hx/ComfyUI/comfyui.log
[ComfyUI-Manager] WARN: Unsafe - SSL verification bypass option is Enabled. (see ComfyUI-Manager/config.ini)

Prestartup times for custom nodes:
   0.7 seconds: /home/hx/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24268 MB, total RAM 128531 MB
pytorch version: 2.3.1+cu118
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.3.1+cu118)
    Python  3.10.11 (you have 3.10.14)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/hx/ComfyUI/web
Successfully imported spandrel_extra_arches: support for non commercial upscale models.
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2781 [915fdb57] | Released on '2024-10-22'

Import times for custom nodes:
   0.0 seconds: /home/hx/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/hx/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://192.168.2.105:7862
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hx/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1365, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/hx/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1362, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "/home/hx/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1349, in get_cache
    json_obj = await core.get_data(uri, True)
  File "/home/hx/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 620, in get_data
    async with session.get(uri) as resp:
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/hx/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
```

this is repo comfyui-manager
![image](https://github.com/user-attachments/assets/0e30495f-18b5-445b-9640-dca12e34a583)

I install it by git:
![image](https://github.com/user-attachments/assets/bc7db5e3-0ff2-4620-8d5d-fe934b914d58)

please help me!

**Comment by ltdrdata** [comment]
See ssl error part.
https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting
