### ISSUE TITLE
Comfy fails to launch after updating  nodes for https://github.com/kijai/ComfyUI-IC-Light

### ISSUE THREAD

**Issue by sexpixel** [Comfy-Org/ComfyUI-Manager#1248]
U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
WARNING: Ignoring invalid distribution ~umpy (U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-19 20:43:19.284627
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI
** Log path: U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   9.3 seconds: \\192.168.1.84\COMFY\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130920 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A5000 : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 397, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 102, in require_version
    got_ver = importlib.metadata.version(pkg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\metadata\__init__.py", line 889, in version
  File "importlib\metadata\__init__.py", line 862, in distribution
  File "importlib\metadata\__init__.py", line 399, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for numpy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\main.py", line 90, in <module>
    import execution
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 18, in <module>
    from . import model_detection
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 104, in require_version
    raise importlib.metadata.PackageNotFoundError(
importlib.metadata.PackageNotFoundError: No package metadata was found for The 'numpy>=1.17' distribution was not found and is required by this application.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main

U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by ltdrdata** [comment]
Execute this in cmd.
```
U:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\python_embeded\pyhon.exe -m pip install -U transformers "numpy<2"
```
