### ISSUE TITLE
ComfyUI crashing at server start after adding new node

### ISSUE THREAD

**Issue by Vegansaregrassfed** [Comfy-Org/ComfyUI-Manager#125]
Running via Nvidia_GPU.bat

ComfyUI was starting normally. Added Lilly Widcard node and on restart I get this error handling request. Then the UI appears, but there's no nodes, no manager button, right clicking bring ups the option for new node or new group, but nothing to load.

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: T:\NewPortComfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "T:\NewPortComfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "T:\NewPortComfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "T:\NewPortComfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "T:\NewPortComfy\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "T:\NewPortComfy\ComfyUI_windows_portable\ComfyUI\server.py", line 416, in get_object_info
    out[x] = node_info(x)
  File "T:\NewPortComfy\ComfyUI_windows_portable\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "T:\NewPortComfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\CheckpointLoaderSimpleText.py", line 27, in INPUT_TYPES
    "default": random.choice(t_checkpoints)
  File "random.py", line 378, in choice
IndexError: list index out of range

**Comment by ltdrdata** [comment]
This error seems to occur only when there are no checkpoint files in the checkpoints. This error should be reported on https://github.com/lilly1987/ComfyUI_node_Lilly/issues.

**Comment by Vegansaregrassfed** [comment]
****There are checkpoints in the checkpoint folder and I've been using ComfyUI without issue.

I will post this in ComfyUI_node_Lilly*****

And I was wrong. Another family member, deleted my checkpoints by mistake.
