### ISSUE TITLE
Unable to load "Node Management" information,

### ISSUE THREAD

**Issue by lvlc233** [Comfy-Org/ComfyUI-Manager#1292]
As shown in the picture, as long as I use these three functions, it will always load. At first I thought I had too many custom nodes, but later I kept only one custom node, but it still loads without showing it, even after reinstalling, it still doesn't work.

Here's the background message:
Update error: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
All extensions are already up-to-date.
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: F:\stable-diffusion-webui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]

![QQ图片20241204142040](https://github.com/user-attachments/assets/d5cb818a-f009-4bbf-857c-49c71a852a70)
![QQ图片20241204142112](https://github.com/user-attachments/assets/d9f47333-7af2-4c6f-b986-e0226f501eaa)

**Comment by ltdrdata** [comment]
What is displayed on browser console?

![image](https://github.com/user-attachments/assets/d9f42290-9905-4bd7-9193-4223c9a8b70b)

**Comment by lvlc233** [comment]
I haven't checked my console yet,
And here's my console message,
Thank you for your answer.
![QQ图片20241206171010](https://github.com/user-attachments/assets/0e0c8043-9a84-4088-8e40-b65b91bbcc7b)
![QQ图片20241206171014](https://github.com/user-attachments/assets/12a6777d-25bd-4e6e-b071-7488ff0ad5ed)

**Comment by ltdrdata** [comment]
Disable all custom nodes except ComfyUI-Manager. And try again.

**Comment by Roon** [comment]
I think I'm having the same, or a very similar, issue. ComfyUI-Manager is the only custom node I have. "Custom Nodes Manager" and "Install Missing Custom Nodes" both hang with this in the console:

> custom-nodes-manager.js:687 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Comfy.ColorPalette')
    at CustomNodesManager.renderGrid (custom-nodes-manager.js:687:59)
    at CustomNodesManager.loadData (custom-nodes-manager.js:1270:8)
renderGrid @ custom-nodes-manager.js:687
loadData @ custom-nodes-manager.js:1270
await in loadData
show @ custom-nodes-manager.js:1375
onclick @ comfyui-manager.js:774

"Model Manager" hangs with this:

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Comfy.ColorPalette')
    at ModelManager.renderGrid (model-manager.js:466:59)
    at ModelManager.loadData (model-manager.js:746:8)

**Comment by ltdrdata** [comment]
> I think I'm having the same, or a very similar, issue. ComfyUI-Manager is the only custom node I have. "Custom Nodes Manager" and "Install Missing Custom Nodes" both hang with this in the console:
> 
> > custom-nodes-manager.js:687 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Comfy.ColorPalette')
> > at CustomNodesManager.renderGrid (custom-nodes-manager.js:687:59)
> > at CustomNodesManager.loadData (custom-nodes-manager.js:1270:8)
> > renderGrid @ custom-nodes-manager.js:687
> > loadData @ custom-nodes-manager.js:1270
> > await in loadData
> > show @ custom-nodes-manager.js:1375
> > onclick @ comfyui-manager.js:774
> 
> "Model Manager" hangs with this:
> 
> > Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Comfy.ColorPalette')
> > at ModelManager.renderGrid (model-manager.js:466:59)
> > at ModelManager.loadData (model-manager.js:746:8)

What is your ComfyUI version?
Please post the `comfyui.log`.

**Comment by Roon** [comment]
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.7-31-ge83063b | Released on '2024-12-14'
[comfyui.log](https://github.com/user-attachments/files/18138924/comfyui.log)

**Comment by ltdrdata** [comment]
Make sure you are using new UI.
If you are using the new UI, try using a different browser.

**Comment by Roon** [comment]
Yeah, it's the new UI. I have the issue in Brave, but not in Firefox. So that's good. One observation - looking at the screenshot of the ComfyUI Manager Menu, there's some spacing between "Double-Click: Copy All Connections" and "Experimental", and between "Install via Git URL" and "Update All", and between "Nodes Info" and the "Issue News" box, and on either side of "Alternatives of A1111". I have those spaces in Brave, but not in Firefox. I wonder what browser @lvlc233 is using.

**Comment by shonlg** [comment]
这个问题，我也碰到了，没有更新前能正常打开，更新到最新的：3.0.1版本这个浏览器里面就打不开了，换了一个浏览器还能正常打开，估计可能和浏览器内核兼容性出了问题，如下图，打开的浏览器内核版本：WebKit 537.36  Chrome 116.0.5845.97 ，能打开的：WebKit 537.36  Chrome 112.0.0.0，供参考：
![01](https://github.com/user-attachments/assets/d9771e7d-63f9-41bb-8b3f-8e418e8403df)

**Comment by GalaxyTimeMachine** [comment]
I'm having the same issue. It does load eventually, but it can take up to 2 minutes. No errors in the console, but the delay is between these two entries:
```
FETCH DATA from: https://api.comfy.org/nodes?page=1&limit=1000 [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes?page=1&limit=1000
```

**Comment by ltdrdata** [comment]
> I'm having the same issue. It does load eventually, but it can take up to 2 minutes. No errors in the console, but the delay is between these two entries:
> 
> ```
> FETCH DATA from: https://api.comfy.org/nodes?page=1&limit=1000 [DONE]
> [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes?page=1&limit=1000
> ```

Update to latest version try again.

**Comment by GalaxyTimeMachine** [comment]
> Update to latest version try again.

Still the same.

**Comment by Popshells** [comment]
In my case, after "updating all" and refreshing the browser, the "Loading custom nodes (cache)..." started working again.

**Comment by ltdrdata** [comment]
This is outdated thread.
Please reopen if this issue still persist.
