### ISSUE TITLE
Broken : × python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by ksorah1** [Comfy-Org/ComfyUI-Manager#133]
Hello,

Since I installed ComfyUI-Manage I started to get this : https://github.com/comfyanonymous/ComfyUI/issues/1737

I've searched for hours, I can't find any solution that works, and their Git seems to have no support. Now I can't even run ComfyUI.

**Comment by ltdrdata** [comment]
I've updated the PyTorch in the manager's notebook to version 2.0.1. Try using it in the new notebook of the manager.

**Comment by ksorah1** [comment]
What is "the notebook of the manager" ?

**Comment by ksorah1** [comment]
When I use the install-manager-for-portable-version.bat I get :
`
```
C:\Users\xxx\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install gitpython
Requirement already satisfied: gitpython in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (3.1.37)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from gitpython) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.1)

C:\Users\xxx\ComfyUI_windows_portable>.\python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/ltdrdata/ComfyUI-Manager', './ComfyUI/custom_nodes/ComfyUI-Manager')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xxx\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\repo\base.py", line 1328, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "C:\Users\xxx\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\repo\base.py", line 1237, in _clone
    finalize_process(proc, stderr=stderr)
  File "C:\Users\xxx\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\util.py", line 437, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\xxx\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/ltdrdata/ComfyUI-Manager ./ComfyUI/custom_nodes/ComfyUI-Manager
  stderr: 'fatal: destination path './ComfyUI/custom_nodes/ComfyUI-Manager' already exists and is not an empty directory.
'

C:\Users\xxx\ComfyUI_windows_portable>pause
Appuyez sur une touche pour continuer...
```
`

**Comment by ksorah1** [comment]
fixed
