### ISSUE TITLE
ComfyUI error NEED HELP! 

### ISSUE THREAD

**Issue by Skidadel** [Comfy-Org/ComfyUI-Manager#1344]
Hi 

After installing all the plugins etc. i can succesfully open ComfyUI and  see the small manager button in the top right corner. But the floating menu won't appear... 

I revieve the following message in the CMD:

C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-18 13:40:51.431676
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   2.7 seconds: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32556 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
### Loading: ControlnetAux (V0.3 beta)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'

Import times for custom nodes:
   0.0 seconds: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.6 seconds: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ControlnetAux

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'controlaux_hed' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_midas' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_mlsd' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_openpose' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_pidi' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_dwpose' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_normal_bae' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart_anime' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_zoe' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_sam' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_leres' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_canny' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_content' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_face_detector' node.
Traceback (most recent call last):
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
Update check done.
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
Update check done.
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\2259715867_alter-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\Users\seg\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
Update check done.

**Comment by ltdrdata** [comment]
It seems that some of the custom nodes you installed are broken.  
Try disabling all custom nodes and testing again.
