### ISSUE TITLE
(IMPORT FAILED): D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use

### ISSUE THREAD

**Issue by JulyHzw** [Comfy-Org/ComfyUI-Manager#1348]
I am certain that diffusers, accelerate, and Simpleeval have been successfully installed in my conda virtual environment, but the error still persists!!! Please help me
Here are some error messages：

[Prompt Server] web root: D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\web
Module 'diffusers' load failed. If you don't have it installed, do it:
pip install diffusers
Traceback (most recent call last):
  File "D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 21, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 26, in <module>
    from .libs.sampler import easySampler, alignYourStepsScheduler, gitsScheduler
  File "D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\sampler.py", line 10, in <module>
    from ..brushnet.model_patch import add_model_patch
  File "D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\brushnet\__init__.py", line 8, in <module>
    from accelerate import init_empty_weights, load_checkpoint_and_dispatch
ModuleNotFoundError: No module named 'accelerate'

Cannot import D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: No module named 'accelerate'

-------------------------------------------------------------------------------------
D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
D:\8.stable-diffusion-demo-project\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

Import times for custom nodes:

**Comment by ltdrdata** [comment]
Why do you use portable version for conda environment?

**Comment by JulyHzw** [comment]
> Why do you use portable version for conda environment?

Because I was not in the Conda environment at the beginning, I encountered this problem. I thought it was an environmental issue, so I created a new Conda environment and reconfigured some package versions inside, but the problem was not solved

**Comment by ltdrdata** [comment]
> > Why do you use portable version for conda environment?
> 
> Because I was not in the Conda environment at the beginning, I encountered this problem. I thought it was an environmental issue, so I created a new Conda environment and reconfigured some package versions inside, but the problem was not solved

Please upload full startup log.

**Comment by JulyHzw** [comment]
> > > Why do you use portable version for conda environment?
> > 
> > 
> > Because I was not in the Conda environment at the beginning, I encountered this problem. I thought it was an environmental issue, so I created a new Conda environment and reconfigured some package versions inside, but the problem was not solved
> 
> Please upload full startup log.

The problem has been resolved, thank you for your valuable time!
