### ISSUE TITLE
When installing Impact subpack in the ComplyUI Desktop version, ultralytics installation problem.

### ISSUE THREAD

**Issue by bluenyx** [Comfy-Org/ComfyUI-Manager#1361]
When installing Impact subpack in the ComplyUI Desktop version, ultralytics installation problem.

1. On initial installation -> Installation failed
2. If you delete and reinstall both impact pack and subpack -> install successfully
3. However, opencv-python is still not installed

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-22 14:22:31.029180
** Platform: Windows
** Python version: 3.12.4 (main, Jul 25 2024, 21:57:00) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Users\bluen\Documents\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\bluen\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** Log path: C:\Users\bluen\Documents\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   2.1 seconds: C:\Users\bluen\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager

### Loading: ComfyUI-Impact-Pack (V8.1.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.1)
No module named 'ultralytics'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

Traceback (most recent call last):
  File "C:\Users\bluen\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\bluen\Documents\ComfyUI\custom_nodes/ComfyUI-Impact-Subpack\__init__.py", line 22, in <module>
    imported_module = importlib.import_module(".modules.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluen\Documents\ComfyUI\uv-cache\cpython-3.12.4-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\bluen\Documents\ComfyUI\custom_nodes/ComfyUI-Impact-Subpack\modules\subpack_nodes.py", line 4, in <module>
    from . import subcore
  File "C:\Users\bluen\Documents\ComfyUI\custom_nodes/ComfyUI-Impact-Subpack\modules\subcore.py", line 45, in <module>
    raise e
  File "C:\Users\bluen\Documents\ComfyUI\custom_nodes/ComfyUI-Impact-Subpack\modules\subcore.py", line 41, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'

Cannot import C:\Users\bluen\Documents\ComfyUI\custom_nodes/ComfyUI-Impact-Subpack module for custom nodes: No module named 'ultralytics'
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\bluen\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

![image](https://github.com/user-attachments/assets/163af0e9-c509-4ccb-b1b3-f66a0aa9349d)
![image](https://github.com/user-attachments/assets/a1953e98-aade-4c69-934a-60f15e9f1de4)
![image](https://github.com/user-attachments/assets/e25404ec-bafe-4580-acb1-3c243b158cc2)
![image](https://github.com/user-attachments/assets/ddb0b18e-79bd-4c06-bef4-6551d1d30d70)
![image](https://github.com/user-attachments/assets/6bd09ee7-cd8c-41af-8671-bb81ad2fd47c)
![image](https://github.com/user-attachments/assets/f277e68a-c4ba-4c8a-9ccc-ba655e7d9a9a)

**Comment by bluenyx** [comment]
[comfyui_8000.log](https://github.com/user-attachments/files/18221378/comfyui_8000.log)
[comfyui_8000.prev.log](https://github.com/user-attachments/files/18221380/comfyui_8000.prev.log)
[comfyui_8000.prev2.log](https://github.com/user-attachments/files/18221381/comfyui_8000.prev2.log)

**Comment by ltdrdata** [comment]
This is resolved.
