### ISSUE TITLE
Installing ComfyUI-Manager on M1 Mac  not successful. Custom-node-list.json issue?

### ISSUE THREAD

**Issue by Martin077** [Comfy-Org/ComfyUI-Manager#138]
I attempted to install ComfyUI-Manager twice on my M1 Mac, once manually via .zip file, and then via cloning. Both times received similar error messages (copied below) and ComfyUI stopped working. I am installing on an external SSD drive (not enough space on my M1 hard drive for dependencies) but I don't have any problem running ComfyUI (without Comfy-UI Manager) or Automatic 1111 from  the external drive. I removed the ComfyUI-Manager files from the "custom_nodes" folder, and ComfyUI worked again. Seems like the installation is having a problem related to the "custom-node-list.json" file? That file is in my ComfyUI-manager folder. Advice appreciated.

Traceback (most recent call last):
  File "/Volumes/SSD 4TB/ComfyUI-master/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scanner.py", line 266, in <module>
    updated_node_info = update_custom_nodes()
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scanner.py", line 163, in update_custom_nodes
    git_url_titles = get_git_urls_from_json('custom-node-list.json')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scanner.py", line 106, in get_git_urls_from_json
    with open(json_file, encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'custom-node-list.json'

Cannot import /Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scanner.py module for custom nodes: [Errno 2] No such file or directory: 'custom-node-list.json'
Traceback (most recent call last):
  File "/Volumes/SSD 4TB/ComfyUI-master/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/js/__init__.py'

Cannot import /Volumes/SSD 4TB/ComfyUI-master/custom_nodes/js module for custom nodes: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/js/__init__.py'
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
Traceback (most recent call last):
  File "/Volumes/SSD 4TB/ComfyUI-master/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scripts/__init__.py'

Cannot import /Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scripts module for custom nodes: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/scripts/__init__.py'
** ComfyUI start up time: 2023-10-13 21:52:43.033794
Skip /Volumes/SSD 4TB/ComfyUI-master/custom_nodes/prestartup_script.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
Traceback (most recent call last):
  File "/Volumes/SSD 4TB/ComfyUI-master/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/node_db/__init__.py'

Cannot import /Volumes/SSD 4TB/ComfyUI-master/custom_nodes/node_db module for custom nodes: [Errno 2] No such file or directory: '/Volumes/SSD 4TB/ComfyUI-master/custom_nodes/node_db/__init__.py'

**Comment by ltdrdata** [comment]
Just you ruined your custom_nodes dir.
Remove all files in custom_nodes dir except `example_node.py.example`
Especially hidden folder `custom_nodes/.git`.

You have to it uncompress as `custom_nodes/ComfyUI-Manager` not `custom_nodes`
And I don't recommend installing through uncompress.

Just open cmd and goto `custom_nodes` dir and 
`git clone https://github.com/ltdrdata/ComfyUI-Manager`

**Comment by Martin077** [comment]
It worked! Thank you very much for the advice. Great product. 👍
