### ISSUE TITLE
Can't fully install and run custom nodes, some nodes stopped working

### ISSUE THREAD

**Issue by DanBoyDan** [Comfy-Org/ComfyUI-Manager#147]
Hi, 

I installed controlnet nodes and played with them for a while while watching and reading tutorials. Suddenly I noticed that the roop node is not loading at the beginning. Also some of the mtb nodes are not loading. I installed everything trough manager, then uninstalled and reinstalled again. Nothing changes.

```
** ComfyUI start up time: 2023-10-17 21:15:27.560874

Prestartup times for custom nodes:
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 12042 MB, total RAM 31952 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loaded efficiency nodes from /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui
Registered sys.path: ['/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/comfy', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/dan/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/tmp/tmpe6w8coym', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui-art-venture/bin', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes']
/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Registered sys.path: ['/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/comfy', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/dan/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/tmp/tmpe6w8coym', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui-art-venture/bin', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes']
Loaded ControlNetPreprocessors nodes from /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
### Loading: ComfyUI-Impact-Pack (V4.23.8)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.31)
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1585 [88ceeb3f] | Released on '2023-10-17'
�[34mOpenPose Editor: �[92mLoaded�[0m
Total VRAM 12042 MB, total RAM 31952 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.0.1+cu118
�[34mComfyroll Custom Nodes: �[92mLoaded�[0m
Registered sys.path: ['/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/comfy', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/comfy', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/home/dan/.local/lib/python3.10/site-packages/git/ext/gitdb', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/media/dan/Local Disk 1TB/AI/ComfyUI/comfy', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/dan/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/tmp/tmpe6w8coym', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui-art-venture/bin', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui', '/media/dan/Local Disk 1TB/AI/ComfyUI', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules', '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack', '/usr/lib/python3/dist-packages/IPython/extensions', '../..']
Traceback (most recent call last):
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop/__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop/nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop/scripts/faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop/scripts/swapper.py", line 12, in <module>
    import insightface
  File "/home/dan/.local/lib/python3.10/site-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/home/dan/.local/lib/python3.10/site-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/home/dan/.local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "/home/dan/.local/lib/python3.10/site-packages/insightface/model_zoo/arcface_onnx.py", line 10, in <module>
    import onnx
  File "/home/dan/.local/lib/python3.10/site-packages/onnx/__init__.py", line 13, in <module>
    from onnx.external_data_helper import (
  File "/home/dan/.local/lib/python3.10/site-packages/onnx/external_data_helper.py", line 11, in <module>
    from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "/home/dan/.local/lib/python3.10/site-packages/onnx/onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/home/dan/.local/lib/python3.10/site-packages/onnx/onnx_ml_pb2.py", line 19, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onnx.onnx_ml_pb2', globals())
  File "/home/dan/.local/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "/home/dan/.local/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop module for custom nodes: A Message class can only inherit from Message
�[36;20m[comfy_mtb] | STATUS -> loaded �[96m48�[0m nodes successfuly�[0m
�[36;20m[comfy_mtb] | STATUS -> Some nodes (7) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.�[0m
Total VRAM 12042 MB, total RAM 31952 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "/media/dan/Local Disk 1TB/AI/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/models/__init__.py'

Cannot import /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/models module for custom nodes: [Errno 2] No such file or directory: '/media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/models/__init__.py'

Import times for custom nodes:
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds (IMPORT FAILED): /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/models
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/masquerade-nodes-comfyui
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/IPAdapter-ComfyUI
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-OpenPose-Editor
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds (IMPORT FAILED): /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI_roop
   0.0 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/facerestore_cf
   0.1 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui-reactor-node
   0.3 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.6 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfy_mtb
   0.6 seconds: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/comfyui-art-venture

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /media/dan/Local Disk 1TB/AI/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
got prompt
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model

100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:53<00:00,  1.19s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:53<00:00,  1.79s/it]
Prompt executed in 112.51 seconds
got prompt
Requested to load SDXL
Loading 1 new model

100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:49<00:00,  1.13s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:49<00:00,  1.66s/it]
Prompt executed in 56.07 seconds
got prompt
Prompt executed in 0.00 seconds
got prompt
got prompt

100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:52<00:00,  1.14s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:52<00:00,  1.74s/it]
Prompt executed in 57.96 seconds
Requested to load SDXL
Loading 1 new model

Prompt executed in 26.69 seconds

Stopped server
```

**Comment by ltdrdata** [comment]
This issue should be directly addressed with the repositories of each custom node.
