### ISSUE TITLE
NameError: name 'model_lora_keys_unet' is not defined

### ISSUE THREAD

**Issue by mio-hu** [Comfy-Org/ComfyUI-Manager#148]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/ai/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/ai/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/ai/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 104, in efficientloader
    model, clip = load_lora(lora_params, ckpt_name, my_unique_id, cache=lora_cache, ckpt_cache=ckpt_cache, cache_overwrite=True)
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 319, in load_lora
    lora_model, lora_clip = recursive_load_lora(lora_params, ckpt, clip, id, ckpt_cache, cache_overwrite, folder_paths)
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 310, in recursive_load_lora
    lora_model, lora_clip = load_lora_for_models_tsc(ckpt, clip, lora_path, strength_model, strength_clip)
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_sd.py", line 122, in load_lora_for_models_tsc
    key_map = model_lora_keys_unet(model.model)
NameError: name 'model_lora_keys_unet' is not defined

Thanks for your time.. 🙏

**Comment by ltdrdata** [comment]
The issue should be reported at https://github.com/LucianoCirino/efficiency-nodes-comfyui.

**Comment by mio-hu** [comment]
> The issue should be reported at https://github.com/LucianoCirino/efficiency-nodes-comfyui.应在 https://github.com/LucianoCirino/efficiency-nodes-comfyui 报告此问题。

ok，Thanks Reply
