### ISSUE TITLE
Update all command broke Comfy Manager and ComfyUI

### ISSUE THREAD

**Issue by azumbrunnen** [Comfy-Org/ComfyUI-Manager#183]
I pressed the update all button and now ComfyUI can't launch anymore.

Here is the traceback. Any ideas?

** ComfyUI start up time: 2023-11-20 18:32:47.105952

Prestartup times for custom nodes:
   0.0 seconds: /Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/main.py", line 69, in <module>
    import comfy.utils
  File "/Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/comfy/utils.py", line 1, in <module>
    import torch
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/torch/__init__.py", line 1504, in <module>
    from . import masked
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/torch/masked/__init__.py", line 3, in <module>
    from ._ops import (
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/torch/masked/_ops.py", line 11, in <module>
    from torch._prims_common import corresponding_real_dtype
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/torch/_prims_common/__init__.py", line 23, in <module>
    import sympy
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/__init__.py", line 74, in <module>
    from .polys import (Poly, PurePoly, poly_from_expr, parallel_poly_from_expr,
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/polys/__init__.py", line 78, in <module>
    from .polyfuncs import (symmetrize, horner, interpolate,
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/polys/polyfuncs.py", line 10, in <module>
    from sympy.polys.specialpolys import (
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/polys/specialpolys.py", line 298, in <module>
    from sympy.polys.rings import ring
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/polys/rings.py", line 30, in <module>
    from sympy.printing.defaults import DefaultPrinting
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/printing/__init__.py", line 3, in <module>
    from .pretty import pager_print, pretty, pretty_print, pprint, pprint_use_unicode, pprint_try_use_unicode
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/printing/pretty/__init__.py", line 7, in <module>
    pprint_try_use_unicode()
  File "/Users/azumbrunnen/miniconda3/lib/python3.11/site-packages/sympy/printing/pretty/pretty_symbology.py", line 81, in pretty_try_use_unicode
    s.encode(encoding)
TypeError: encode() argument 'encoding' must be str, not method

**Comment by ltdrdata** [comment]
OMG... update again... to `V1.1.2`
