### ISSUE TITLE
UI manager tries to update comfy and then throws an error on start, everytime after install.

### ISSUE THREAD

**Issue by stephantual** [Comfy-Org/ComfyUI-Manager#271]
After installing comfyUI-manager, i can't restart comfy ui portable. I had installed everything the same day, today, from GH. 
From the logs it looks like it's trying to auto update or something, even though i had set the 'skip update check' in the UI.

Is the "fix" removing the manager permanently?

```
C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto
[ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'comfyui.log' -> 'comfyui.prev.log'
** ComfyUI startup time: 2023-12-27 20:36:55.549482
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65338 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Manager (V1.17)
## ComfyUI-Manager: installing dependencies
 Requirement already satisfied: GitPython in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (3.1.40)
 Requirement already satisfied: matrix-client==0.4.0 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (0.4.0)
 Requirement already satisfied: requests~=2.22 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (2.31.0)
 Requirement already satisfied: urllib3~=1.21 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (1.26.18)
 Requirement already satisfied: gitdb<5,>=4.0.1 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (4.0.11)
 Requirement already satisfied: smmap<6,>=3.0.1 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (5.0.1)
 Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (3.3.2)
 Requirement already satisfied: idna<4,>=2.5 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (3.6)
 Requirement already satisfied: certifi>=2017.4.17 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (2023.11.17)
## [ERROR] ComfyUI-Manager: Attempting to reinstall dependencies using an alternative method.
 Requirement already satisfied: GitPython in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (3.1.40)
 Requirement already satisfied: matrix-client==0.4.0 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (0.4.0)
 Requirement already satisfied: requests~=2.22 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (2.31.0)
 Requirement already satisfied: urllib3~=1.21 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (1.26.18)
 Requirement already satisfied: gitdb<5,>=4.0.1 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (4.0.11)
 Requirement already satisfied: smmap<6,>=3.0.1 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (5.0.1)
 Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (3.3.2)
 Requirement already satisfied: idna<4,>=2.5 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (3.6)
 Requirement already satisfied: certifi>=2017.4.17 in c:\ai\comfyui_windows_portable\python_embeded\lib\site-packages (from requests~=2.22->matrix-client==0.4.0->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 2)) (2023.11.17)
## [ERROR] ComfyUI-Manager: Failed to install the GitPython package in the correct Python environment. Please install it manually in the appropriate environment. (You can seek help at https://app.element.io/#/room/%23comfyui_space%3Amatrix.org)
## ComfyUI-Manager: installing dependencies done.
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   2.8 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 224, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 128, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 617, in start
    await site.start()
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1525, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

```

**Comment by ltdrdata** [comment]
1. `skip update check` simply determines whether to check for updates and show the update button when displaying the list.

2. The reason it appears to install something at startup is that in the case of Windows, after installing a custom node or updating, the changes are not applied immediately but take effect upon restarting. Under normal circumstances, once the installation is complete, the installation reservation file is deleted, and it should not appear on the next startup.
(You can find the corresponding file in `custom_nodes\ComfyUI-Manager\startup-scripts`.)

3. The symptom of being unable to start ComfyUI and looking at the logs indicates that there is already a running instance of ComfyUI.
Close any previously opened terminals or similar instances. If you're unsure where to close it, the simplest method is to reboot.

Providing additional information, when running a batch file like 'run_gpu.bat' in the portable version and `restart` through ComfyUI-Manager, you may need to press ctrl-c twice in the terminal to completely shut it down. Pressing ctrl-c only once will close only the batch file, and ComfyUI itself will continue running in the background.

https://github.com/comfyanonymous/ComfyUI/pull/1814#issuecomment-1827102579

**Comment by stephantual** [comment]
Thank you. This was useful to understand. I appreciate your help
