### ISSUE TITLE
Likely user error

### ISSUE THREAD

**Issue by BDColvin** [Comfy-Org/ComfyUI-Manager#29]
After attempted install, I'm getting the following error on ComfyUI startup.

```
Using xformers cross attention
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1516, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git module for custom nodes: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'
```

**Comment by ltdrdata** [comment]
Yeah. This error is occurred by uncompress zip file to invalid directory.

I think that I have to change installation guide on civitai.

You have to remove hidden folder "custom_nodes/.git"


I added this installation script recently.

https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only

**Comment by BDColvin** [comment]
That did it! Thank you for the quick response!!
