### ISSUE TITLE
socket.gaierror: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by cardenluo** [Comfy-Org/ComfyUI-Manager#296]
Exception in thread Thread-6 (<lambda>):
Traceback (most recent call last):
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "asyncio\base_events.py", line 863, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\Blender_ComfyUI_aki\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2153, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "F:\Blender_ComfyUI_aki\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2151, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "F:\Blender_ComfyUI_aki\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2139, in get_cache
    json_obj = await get_data(uri)
  File "F:\Blender_ComfyUI_aki\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 515, in get_data
    async with session.get(uri) as resp:
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]

WARNING:tensorflow:From F:\Blender_ComfyUI_aki\python_embeded\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

**Comment by ltdrdata** [comment]
This is an issue related to your network environment. Check if the following path is accessible in your browser

https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by cardenluo** [comment]
This is weird, the network seems to be fine too. Other functions do not seem to be affected, and lost nodes can also be found and installed. The only problem is that nodes cannot be updated automatically
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/133877069/7c681f3a-36d1-46f9-8a6b-2ce69ff02856)

**Comment by ltdrdata** [comment]
> This is weird, the network seems to be fine too. Other functions do not seem to be affected, and lost nodes can also be found and installed. The only problem is that nodes cannot be updated automatically

What do you mean by **automatic updates don't work**? The Manager never performs automatic updates under any circumstances.

**Comment by cardenluo** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/133877069/9eb50699-2e0d-4027-bffb-b17cf58304c8)
I mean it can't be updated

**Comment by cardenluo** [comment]
I found the reason. When I use other launchers, this situation will occur. If I use the portable version of the built-in launcher, there will be no error.

**Comment by ltdrdata** [comment]
> I found the reason. When I use other launchers, this situation will occur. If I use the portable version of the built-in launcher, there will be no error.

What launcher did you used?

**Comment by stephantual** [comment]
I had a similar issue i listed at https://github.com/ltdrdata/ComfyUI-Manager/issues/359
I closed it becaues it's a cache issue - that's why you have variable results depending if you launch CPU or GPU. 
A gitpull, a little modification of the config file and a cold reboot fixes it. It's very strange because it's cache related so frustrating to debug. But it's not fatal.
