### ISSUE TITLE
Update all - AssertionError

### ISSUE THREAD

**Issue by Piscabo** [Comfy-Org/ComfyUI-Manager#301]
Update ComfyUI
CUSTOM NODE PULL: Success
Install: pip packages
Task exception was never retrieved
future: <Task finished name='Task-43' coro=<RequestHandler.start() done, defined at C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py:481> exception=AssertionError()>
Traceback (most recent call last):
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_app.py", line 485, in _make_request
    return _cls(
           ^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 825, in __init__
    super().__init__(*args, **kwargs)
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 195, in __init__
    assert transport is not None
AssertionError
Task exception was never retrieved
future: <Task finished name='Task-298' coro=<RequestHandler.start() done, defined at C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py:481> exception=AssertionError()>
Traceback (most recent call last):
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_app.py", line 485, in _make_request
    return _cls(
           ^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 825, in __init__
    super().__init__(*args, **kwargs)
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 195, in __init__
    assert transport is not None
AssertionError

**Comment by ltdrdata** [comment]
Update and try again.

**Comment by Piscabo** [comment]
> Update and try again.

Thanks, it seems fixed now. I wish all node owners were this proactive!
