### ISSUE TITLE
ComfyUI Manager fails to install custom nodes (huggingface_hub)

### ISSUE THREAD

**Issue by levsha-designer** [Comfy-Org/ComfyUI-Manager#305]
Hello. I'm trying to install any custom nodes and always receive a message: installation failed. At the same time there is a message in the log:

```
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Update custom node 'ComfyUI-Manager'
Update: ['https://github.com/ltdrdata/ComfyUI-Manager']
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\git_helper.py", line 7, in <module>
    from torchvision.datasets.utils import download_url
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\exporter.py", line 42, in <module>
    from torch.onnx._internal.fx import (
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\fx\__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\fx\patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Roaming\Python\Python311\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\Павел\AppData\Roaming\Python\Python311\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Павел\AppData\Roaming\Python\Python311\site-packages\transformers\utils\__init__.py", line 61, in <module>
    from .hub import (
  File "C:\Users\Павел\AppData\Roaming\Python\Python311\site-packages\transformers\utils\hub.py", line 94, in <module>
    PYTORCH_PRETRAINED_BERT_CACHE = os.getenv("PYTORCH_PRETRAINED_BERT_CACHE", constants.HF_HUB_CACHE)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'
```

If anyone can give me an advice how to fix it, I would be very grateful.

**Comment by ltdrdata** [comment]
It seems your `transformers` package is outdated.

Edit: On the contrary, It seems that your `huggingface-hub` is outdated. It appears that compatibility has been broken as the version of `transformers` has been updated.

Execute this in cmd

```
C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U huggingface-hub
```

**Comment by chen7618** [comment]
What to do with Mac.

**Comment by ltdrdata** [comment]
> What to do with Mac.

You need to install it using pip in the Python environment (e.g., venv, conda, etc.) where you are running ComfyUI.
