### ISSUE TITLE
Error during start of ComfUI

### ISSUE THREAD

**Issue by MoonMoon82** [Comfy-Org/ComfyUI-Manager#331]
Even after updating  ComfyUI Manager I get this error message during start of ComfyUI:

```
e:\StableDiffusion\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --highvram --windows-standalone-build --listen --dont-upcast-attention --disable-xformers --disable-auto-launch --preview-method auto
** ComfyUI startup time: 2024-01-15 15:21:29.166001
** Platform: Windows
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
** Python executable: e:\StableDiffusion\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: e:\StableDiffusion\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 65459 MB
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
disabling upcasting of attention
Using pytorch cross attention
[Crystools INFO] Crystools version: 1.9.1
[Crystools INFO] CPU: AMD Ryzen 9 5950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] NVIDIA Driver detected - 536.23 - cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V4.66.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Inspire-Pack (V0.59)
[Impact Pack] Wildcards loading done.
/_\ Checking packages
/_\ Installing pillow
### Loading: ComfyUI-Manager (V2.0.1)
### ComfyUI Revision: 1911 [f9e55d84] | Released on '2024-01-15'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
OpenPose Editor: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Exception in thread Thread-13 (<lambda>):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2311, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2309, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2297, in get_cache
    json_obj = await get_data(uri)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 531, in get_data
    json_obj = json.loads(json_text)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788)
```
[...]

Afterwards ComfyUI Manager is not active anymore :( 

Any ideas or advices?

**Comment by MoonMoon82** [comment]
Update: It seems ComfiUI Manager is active, but I cant fetch any updates or install custom nodes. Everytime this message appears:

```
FETCH DATA from: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Expecting ',' delimiter: line 4249 column 9 (char 210788)
FETCH DATA from: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Expecting ',' delimiter: line 4249 column 9 (char 210788)
FETCH DATA from: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Expecting ',' delimiter: line 4249 column 9 (char 210788)
FETCH DATA from: E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 609, in get_data_by_mode
    json_obj = await get_data(uri)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 531, in get_data
    json_obj = json.loads(json_text)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "e:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "e:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "e:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 877, in fetch_customnode_list
    json_obj = await get_data_by_mode(request.rel_url.query["mode"], 'custom-node-list.json')
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 622, in get_data_by_mode
    json_obj = await get_data(uri)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 531, in get_data
    json_obj = json.loads(json_text)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788)
```

**Comment by TPreece101** [comment]
I am getting the same:

```
Exception in thread Thread-2 (<lambda>):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2311, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2309, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2297, in get_cache
    json_obj = await get_data(uri)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 531, in get_data
    json_obj = json.loads(json_text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788)
```

**Comment by TPreece101** [comment]
Ah it looks like 2 people have already jumped in with fixes:
https://github.com/ltdrdata/ComfyUI-Manager/pull/329
https://github.com/ltdrdata/ComfyUI-Manager/pull/330

**Comment by ltdrdata** [comment]
oh.. this is my fault... this is fixed.
