### ISSUE TITLE
Remove ComfyUI-DragNUWA, ComfyUI-AnimateAnyone-Evolved from default channel node list until they don't break ComfyUI completely

### ISSUE THREAD

**Issue by NeedsMoar** [Comfy-Org/ComfyUI-Manager#344]
I'm on (or was on) Torch 2.1.2-cu121 on Windows;  installing DragNUWA caused this BS to happen -- 

```cmd
## Execute install/(de)activation script for 'C:\Programs\ComfyUI\custom_nodes\ComfyUI-DragNUWA'
 Collecting torchdata==0.6.1
   Downloading torchdata-0.6.1-cp311-cp311-win_amd64.whl (1.3 MB)
      ---------------------------------------- 1.3/1.3 MB 11.8 MB/s eta 0:00:00
Collecting torch==2.0.1 (from torchdata==0.6.1)
   Downloading torch-2.0.1-cp311-cp311-win_amd64.whl (172.3 MB)
      ------------------------------------- 172.3/172.3 MB 46.7 MB/s eta 0:00:00

 Installing collected packages: torch, torchdata
   Attempting uninstall: torch
     Found existing installation: torch 2.1.2+cu121
     Uninstalling torch-2.1.2+cu121:
       Successfully uninstalled torch-2.1.2+cu121
[!] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
 Successfully installed torch-2.0.1 torchdata-0.6.1
[!] torchaudio 2.1.2+cu121 requires torch==2.1.2+cu121, but you have torch 2.0.1 which is incompatible.
[!] torchvision 0.16.2+cu121 requires torch==2.1.2+cu121, but you have torch 2.0.1 which is incompatible.
[!] xformers 0.0.23.post1 requires torch==2.1.2, but you have torch 2.0.1 which is incompatible.
```

Then AnimateAnyone caused this immediately after so at least I'll only be fixing it once.
```cmd
## Execute install/(de)activation script for 'C:\Programs\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved'
 Collecting clip@ https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip#sha256=b5842c25da441d6c581b53a5c60e0c2127ebafe0f746f8e15561a006c6c3be6a
   Downloading https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip (4.3 MB)
 INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
 Collecting torchvision (from clip@ https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip#sha256=b5842c25da441d6c581b53a5c60e0c2127ebafe0f746f8e15561a006c6c3be6a)
   Downloading torchvision-0.16.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
 Collecting torch (from clip@ https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip#sha256=b5842c25da441d6c581b53a5c60e0c2127ebafe0f746f8e15561a006c6c3be6a)
   Using cached torch-2.1.2-cp311-cp311-win_amd64.whl.metadata (26 kB)
...
 Using cached torch-2.1.2-cp311-cp311-win_amd64.whl (192.3 MB)
 Installing collected packages: torch, torchvision
   Attempting uninstall: torch
     Found existing installation: torch 2.0.1
     Uninstalling torch-2.0.1:
       Successfully uninstalled torch-2.0.1
   Attempting uninstall: torchvision
     Found existing installation: torchvision 0.16.2+cu121
     Uninstalling torchvision-0.16.2+cu121:
       Successfully uninstalled torchvision-0.16.2+cu121
[!] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
 Successfully installed torch-2.1.2 torchvision-0.16.2
[!] torchaudio 2.1.2+cu121 requires torch==2.1.2+cu121, but you have torch 2.1.2 which is incompatible.
[!] torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.2 which is incompatible.

```
And naturally since the extensions removed all the CUDA versions of torch for some braindead reason, this happens when comfy starts:

```cmd
[ComfyUI-Manager] Startup script completed.
#######################################################################

[ComfyUI-Manager] Windows event loop policy mode enabled

Prestartup times for custom nodes:
   0.0 seconds: C:\Programs\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Programs\ComfyUI\custom_nodes\ComfyUI-Marigold
  98.4 seconds: C:\Programs\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Programs\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\Programs\ComfyUI\execution.py", line 14, in <module>
    import nodes
  File "C:\Programs\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\Programs\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\Programs\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Programs\ComfyUI\comfy\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Programs\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Python311\Lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Programs\Python311\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

Even if wheels are pulled correctly on other platforms than Windows (and I can't picture a scenario where these deps will work out correctly for all situations): 
1. I don't care about those platforms.
2. Downgrading torch without permission should never happen regardless, since everything needs it.  Same goes with anything on a CUDA / RoCM / DirectML / IPEX versioning on general principle for that matter.

Now I'm off to uninstall whatever is broken and reinstall torch, which I just love doing.

**Comment by ltdrdata** [comment]
I added warning message for them.
