### ISSUE TITLE
Two (likely related) issues relating to talking to host raw.githubusercontent.com:443 ssl:default

### ISSUE THREAD

**Issue by stephantual** [Comfy-Org/ComfyUI-Manager#359]
I have to errors that started Immediately after I removed 'comfyspace' as a node from comfyui using the manager. Comfy itself is running the latest gitpull as of 1/23/24.

The first is on startup, i get: 

```
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2335, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2333, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2321, in get_cache
    json_obj = await get_data(uri)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 530, in get_data
    async with session.get(uri) as resp:
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
```

The second is simply clicking the 'manager' button which shows this:

![cbwSO2q9lc](https://github.com/ltdrdata/ComfyUI-Manager/assets/1596070/94c547ba-fbd1-4379-abd7-4d020e5359bd)

while the console prints that:
```
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 1818, in get_notice
    conn.request("GET", path)
  File "http\client.py", line 1286, in request
  File "http\client.py", line 1332, in _send_request
  File "http\client.py", line 1281, in endheaders
  File "http\client.py", line 1041, in _send_output
  File "http\client.py", line 979, in send
  File "http\client.py", line 1451, in connect
  File "http\client.py", line 945, in connect
  File "socket.py", line 827, in create_connection
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
```

I tested the connection of course and I'm not vpned, or firewalled. i tried a different netwrok, same problem. 
The issue is that i'm not sure how to even start how to fix this myself given i can ping and use  raw.githubusercontent.com:443 ssl:default without issue outside of comfyui manager.

Thank you.

**Comment by stephantual** [comment]
For reference i'm able to see https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json without issue, and i do have a config.ini file, and yes I tried to bypassSSL=true just in case, none of this work. I restarted the whole machine, same issue.

I can't figure out what's causing this.

**Comment by stephantual** [comment]
Ok i'm going to close this myself - it seems to be a cache issue linked to the uninstalling of certain (but not all) nodes that make API calls to github for reasons that are too hard to decipher due to the fact that I have a bazillion of those installed. 
Gitpull , refresh, FULL cold boot restart, and voila, it works again for anyone having issues. 
i hope this helps someone reading this one day.

**Comment by HobotGob** [comment]
> Ok i'm going to close this myself - it seems to be a cache issue linked to the uninstalling of certain (but not all) nodes that make API calls to github for reasons that are too hard to decipher due to the fact that I have a bazillion of those installed. Gitpull , refresh, FULL cold boot restart, and voila, it works again for anyone having issues. i hope this helps someone reading this one day.

Hi, Can you please explain  step by spet how to do this?
