### ISSUE TITLE
Error while fetching data when trying to install custom nodes

### ISSUE THREAD

**Issue by halicea7** [Comfy-Org/ComfyUI-Manager#416]
Not sure why this is happening. I tried both python 3.12 and 3.11 just in case it might've been an issue with the python version itself. 

```
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2359, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2356, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "/root/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 2344, in get_cache
    json_obj = await get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 547, in get_data
    async with session.get(uri) as resp:
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/modules/apps/anaconda3/envs/debugcomfy/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
[ComfyUI-Manager] Due to a network error, switching to local mode.


```

**Comment by ltdrdata** [comment]
What about opening "Install custom nodes" in the Manager menu after ComfyUI launching is complete?

**Comment by halicea7** [comment]
> What about opening "Install custom nodes" in the Manager menu after ComfyUI launching is complete?

Same thing happens when opening "install custom nodes". I think it might be a problem with asyncio but I'm not sure if you have any clues about fixing this

**Comment by ltdrdata** [comment]
Can you open this on browser without any issue?
https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by halicea7** [comment]
> Can you open this on browser without any issue? https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Yup, it's running on a server and I'm able to curl it just fine.

**Comment by halicea7** [comment]
Any updates?

**Comment by ltdrdata** [comment]
I have written three diagnostic codes below. Remove the `.txt` and try execute each code in your Python environment for ComfyUI.

[t1.py.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14395691/t1.py.txt)
[t2.py.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14395692/t2.py.txt)
[t3.py.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14395693/t3.py.txt)

**Comment by halicea7** [comment]
T1:
`/root/t1.py:10: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
  async with aiohttp.ClientSession(trust_env=True, connector=aiohttp.TCPConnector(verify_ssl=False)) as session:
Traceback (most recent call last):
  File "/root/t1.py", line 27, in <module>
    asyncio.run(test1())
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/t1.py", line 23, in test1
    json_obj = await get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/t1.py", line 11, in get_data
    async with session.get(uri) as resp:
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError`

T2:

`/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
T2: SUCCESS`

T3: 

`/root/t3.py:23: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
/root/t3.py:10: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
  async with aiohttp.ClientSession(trust_env=True, connector=aiohttp.TCPConnector(verify_ssl=False)) as session:
Traceback (most recent call last):
  File "/root/t3.py", line 28, in <module>
    test3()
  File "/root/t3.py", line 24, in test3
    json_obj = loop.run_until_complete(get_data(uri, True))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/t3.py", line 11, in get_data
    async with session.get(uri) as resp:
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/modules/apps/anaconda3/envs/comfyui/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError`

**Comment by halicea7** [comment]
Any updates?

**Comment by ltdrdata** [comment]
> Any updates?

Can you test it venv other than anaconda environment?
