### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by rdcoder33** [Comfy-Org/ComfyUI-Manager#448]
Hi, 
I am trying to run ComfyUI on a fresh runpod GPU instance, ComfyUI-Manager used to work on this setup just a week ago but, not the button is not showing up.

I have no other custom noders installed just the manager.

No error in run log:

```
(venv) root@c4e1ae9c6fe0:/workspace/ComfyUI# python3.10 main.py --listen 0.0.0.0 --port 3000
** ComfyUI startup time: 2024-02-29 03:39:47.449461
** Platform: Linux
** Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
** Python executable: /workspace/ComfyUI/venv/bin/python3.10
** Log path: /workspace/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 20178 MB, total RAM 63426 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4500 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.8.3)
### ComfyUI Revision: 2029 [b3e97fc7] | Released on '2024-02-28'

Import times for custom nodes:
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://0.0.0.0:3000
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

But console log from inspect gives this:

```
a1111-alter-downloader.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
app.js:1361 Error loading extension /extensions/ComfyUI-Manager/a1111-alter-downloader.js TypeError: Failed to fetch dynamically imported module: http://localhost:3000/extensions/ComfyUI-Manager/a1111-alter-downloader.js
(anonymous) @ app.js:1361
comfyui-share-openart.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
app.js:1361 Error loading extension /extensions/ComfyUI-Manager/comfyui-share-openart.js TypeError: Failed to fetch dynamically imported module: http://localhost:3000/extensions/ComfyUI-Manager/comfyui-share-openart.js
(anonymous) @ app.js:1361
components-manager.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
app.js:1361 Error loading extension /extensions/ComfyUI-Manager/components-manager.js TypeError: Failed to fetch dynamically imported module: http://localhost:3000/extensions/ComfyUI-Manager/components-manager.js
```

I also tried to run this in incognito mode but same issue. I am on Mac m1 and there is no antivirus or ad blocker installed. Also tried it on different ports, but no help.

Also, when i try to load any workflow, i get this:

Loading aborted due to error reloading workflow data

```
TypeError: Cannot read properties of undefined (reading 'configure')
TypeError: Cannot read properties of undefined (reading 'configure')
    at ComfyApp.loadGraphData (http://localhost:3000/scripts/app.js:1767:15)
    at async app.loadGraphData (http://localhost:3000/extensions/core/undoRedo.js:25:12)
    at async reader.onload (http://localhost:3000/scripts/app.js:2123:6)
This may be due to the following script:
/extensions/core/undoRedo.js
```

As you can see ComfyManager button is not showing up:

<img width="1440" alt="Screenshot 2024-02-29 at 9 14 49 AM" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/38337897/234b6bfc-ecea-47cb-9890-d3cdcc88bdb7">

**Comment by ltdrdata** [comment]
Did you happen to move the custom node using symbolic links to another location?
