### ISSUE TITLE
Error with fresh installation of Comfyui

### ISSUE THREAD

**Issue by derpmagician** [Comfy-Org/ComfyUI-Manager#589]
I downloaded the new version of the portable link of the repo (the file is called new_ComfyUI_windows_portable_nvidia_cu121_or_cpu) and unzip it in a folder (ComfyUI executed with no errors)
then i cloned the manager repo on custom_nodes, ComfyUI still executed with no errors.

BUT when in pressed the Manager button the error below shows up, the manager still opens and i can still install nodes.

Updating ComfyUI still gives me the error when pressing the Manager button

```
To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.jsonFETCH DATA from: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 53, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1097, in get_notice
    markdown_content += f"<BR>Manager: {version_str}"
                                        ^^^^^^^^^^^
NameError: name 'version_str' is not defined
```

**Comment by ltdrdata** [comment]
Oh... This is fixed now.
