### ISSUE TITLE
NameError: name 'comfy_ui_revision' is not defined / ComfyUI update fail: name 'git' is not defined

### ISSUE THREAD

**Issue by ricperry** [Comfy-Org/ComfyUI-Manager#600]
Not sure if this is a ComfyUI-Manager or a ComfyUI problem, but only recently I can no longer update either ComfyUI or Custom Nodes with the manager button. The only way I seem to be able to update anything is a `git pull` in each custom-node directory. I'm on Linux (Ubuntu 22.04.4) with all my packages up to date. No custom tweaks.

```
FETCH DATA from: ~/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "~/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "~/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "~/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "~/ComfyUI/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "~/ComfyUI/server.py", line 53, in cors_middleware
    response = await handler(request)
  File "~/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 1164, in get_notice
    markdown_content += f"<HR>ComfyUI: {comfy_ui_revision}[{comfy_ui_hash[:6]}]({comfy_ui_commit_datetime.date()})"
NameError: name 'comfy_ui_revision' is not defined
Update ComfyUI
ComfyUI update fail: name 'git' is not defined
```

**Comment by ltdrdata** [comment]
The version you installed was temporarily broken. 
`git pull` is the only way.
