### ISSUE TITLE
ComfUI Install custom nodes super slow

### ISSUE THREAD

**Issue by zono50** [Comfy-Org/ComfyUI-Manager#604]
How long should this take to load typically? It seemed to be working fine before i got my router switched out, and now it takes like 5 or 10 minutes to swap out. i'm getting 80 mbps download and it was never this slow before. I'm using anaconda as well, and i did update my comfyui to the latest. I've also tried removeing comfyui-manager, reinstalling it, and doing sudo chmod 755 -R * to setup permisssions, but still seems to take forever to load. A week ago, it loaded instantly.

Also getting this error - Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1615, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1612, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1600, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 570, in get_data
    async with session.get(uri) as resp:
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> extension-node-map.json

**Comment by zono50** [comment]
Also tried deleting the folder itself, restarted COmfyui, stopped COmfyui, went to custom nodes fold and reinstalled manually.

then did a git clone for manager

restarted comfy and manager still doing the same thing.

**Comment by ltdrdata** [comment]
It seems that there is an issue with the your network settings.

Did you mean that the code is slow, but it works?
https://github.com/ltdrdata/ComfyUI-Manager/issues/601#issuecomment-2072398551


What about directly opening https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json in the browser?

**Comment by Amit30swgoh** [comment]
What do you mean "directly opening https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json in the browser?" not via colab cloudflare? btw if i use T4 GPU colab pro 15GBVRAM can i add something like --opt-split-attention ? i get many times out of memory also many times it seems like the Vram stucks is there a way to auto clean/flush vram after generating photo? ty so much

**Comment by Amit30swgoh** [comment]
> Reference in n

What do you mean "directly opening https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json in the browser?" not via colab cloudflare? btw if i use T4 GPU colab pro 15GBVRAM can i add something like --opt-split-attention ? i get many times out of memory also many times it seems like the Vram stucks is there a way to auto clean/flush vram after generating photo? ty so much

**Comment by ltdrdata** [comment]
> > Reference in n
> 
> What do you mean "directly opening https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json in the browser?" not via colab cloudflare? btw if i use T4 GPU colab pro 15GBVRAM can i add something like --opt-split-attention ? i get many times out of memory also many times it seems like the Vram stucks is there a way to auto clean/flush vram after generating photo? ty so much

Is your ComfyUI environemnt colab + cloudflare?

**Comment by Amit30swgoh** [comment]
yes sir soryy for the delay
