### ISSUE TITLE
Please help! Problem with error: mixed dtype (CPU): expect parameter to have scalar type of Float

### ISSUE THREAD

**Issue by Maxymal78** [Comfy-Org/ComfyUI-Manager#618]
https://openart.ai/workflows/animanon/anis-txt2img2vid-workflow/l27UI6IJSqqPvC2e2SMs my workplace

I have a problem, when I turn on the queue, everything goes great until the progress bar reaches 90%. In this moment Ksampler (Advanced) starts working on workplace. Then a red error pops up with information:

[2024-04-26 15:18] !!! Exception during processing!!! mixed dtype (CPU): expect parameter to have scalar type of Float

[2024-04-26 15:18] Traceback (most recent call last):

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\[execution.py](https://execution.py/)", line 151, in recursive_execute

output_data, output_ui = get_output_data(obj, input_data_all)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\[execution.py](https://execution.py/)", line 81, in get_output_data

return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\[execution.py](https://execution.py/)", line 74, in map_node_over_list

results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1378, in sample

return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\[nodes.py](https://nodes.py/)", line 1314, in common_ksampler

samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample

raise e

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample

return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\[sampling.py](https://sampling.py/)", line 383, in motion_sample

latents = orig_comfy_sample(model, noise, *args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample

return orig_comfy_sample(model, *args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[sample.py](https://sample.py/)", line 37, in sample

samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 755, in sample

return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 657, in sample

return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 644, in sample

output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 623, in inner_sample

samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 534, in sample

samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\[sampling.py](https://sampling.py/)", line 154, in sample_euler_ancestral

denoised = model(x, sigmas[i] * s_in, **extra_args)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 272, in __call__

out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 610, in __call__

return self.predict_noise(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 613, in predict_noise

return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\[sampling.py](https://sampling.py/)", line 428, in evolved_sampling_function

cond_pred, uncond_pred = sliding_calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\[sampling.py](https://sampling.py/)", line 572, in sliding_calc_cond_uncond_batch

sub_cond_out, sub_uncond_out = comfy.samplers.calc_cond_batch(model, [sub_cond, sub_uncond], sub_x, sub_timestep, model_options)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[samplers.py](https://samplers.py/)", line 218, in calc_cond_batch

output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 97, in apply_model

model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1511, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1520, in _call_impl

return forward_call(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\[openaimodel.py](https://openaimodel.py/)", line 850, in forward

h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\[sampling.py](https://sampling.py/)", line 101, in forward_timestep_embed

x = layer(x, context)

^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1511, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1520, in _call_impl

return forward_call(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 673, in forward

return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask, self.view_options, mm_kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1511, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1520, in _call_impl

return forward_call(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 882, in forward

hidden_states = self.norm(hidden_states).to(hidden_states.dtype)

^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1511, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1520, in _call_impl

return forward_call(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\ComfyUI\comfy\[ops.py](https://ops.py/)", line 94, in forward

return super().forward(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\GIT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\[sampling.py](https://sampling.py/)", line 140, in groupnorm_mm_forward

input = group_norm(input, self.num_groups, weight, bias, self.eps)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "d:\GIT\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\[functional.py](https://functional.py/)", line 2561, in group_norm

return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float

[2024-04-26 15:18] Prompt executed in 1076.69 seconds

**Comment by ltdrdata** [comment]
You'd better ask that issue to here:
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved
