### ISSUE TITLE
raise asyncio.timeouterror everytime I try to view Nodes

### ISSUE THREAD

**Issue by zono50** [Comfy-Org/ComfyUI-Manager#634]
I was told previously that this was a network issue, so i wiped my entire OS, and installed a different OS. I went from Manjaro to Arch Linux. I also went into my pfsense router, and set 8.8.8.8 and 8.8.4.4 as my google static DNS.  Did a fresh install of Comfy, and everything on my network has been great. Getting 0% packet loss. As soon as i install the comfyui-manager, and try to view nodes, i get the following message - 

Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1579, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1576, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "/home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1564, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 571, in get_data
    async with session.get(uri) as resp:
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 507, in _request
    with timer:
  File "/home/zono50/.conda/envs/comfy/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
FETCH DATA from: /home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> 
FETCH DATA from: /home/zono50/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Anyone smarter than me that can help with this I would greatly appreciate it. I love ComfyUI, and I also love the convenience of the ComfUI manager, but can't use it if it takes 20 minutes to load anything.

**Comment by zono50** [comment]
Update - apparently my IPV6 was being blocked by my isp's new modem/router, so went into arch linux, created a 99-sysctl.conf file, and input the following - 

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

applied the settings with sudo sysctl --system

and now everything works great. Sorry about the bug report
