### ISSUE TITLE
"No module named 'kornia'"

### ISSUE THREAD

**Issue by norfuer** [Comfy-Org/ComfyUI-Manager#635]
Hi, first time user. Trying to transition from A1111 to here... Zero coding knowhow. But I have some basic reading and comprehension, and I've had some trouble importing nodes_canny and nodes_morphology because of a missing module called... kornia?

Thanks for your help!

Here's the log, if my description isn't useful:
```
/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
updated 1 package in 1.101s
** ComfyUI startup time: 2024-05-01 18:06:01.749715
** Platform: Linux
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
** Python executable: /usr/bin/python3
** Log path: /content/drive/MyDrive/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 15102 MB, total RAM 12979 MB
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_canny.py", line 7, in <module>
    from kornia.filters import canny
ModuleNotFoundError: No module named 'kornia'

Cannot import /content/drive/MyDrive/ComfyUI/comfy_extras/nodes_canny.py module for custom nodes: No module named 'kornia'
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_morphology.py", line 4, in <module>
    from kornia.morphology import dilation, erosion, opening, closing, gradient, top_hat, bottom_hat
ModuleNotFoundError: No module named 'kornia'

Cannot import /content/drive/MyDrive/ComfyUI/comfy_extras/nodes_morphology.py module for custom nodes: No module named 'kornia'
### Loading: ComfyUI-Manager (V2.24.1)
### ComfyUI Revision: 2153 [2aed53c4] | Released on '2024-04-30'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
### Loading: ComfyUI-Impact-Pack (V5.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------

Import times for custom nodes:
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/websocket_image_save.py
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_canny.py
IMPORT FAILED: nodes_morphology.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt
```

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/d37cd64a-d271-403d-a813-ba1a70be26d8)

Select install pip packages.
And input `kornia>=0.7.1`

It seems that you didn't install `requirements.txt` after update your ComfyUI.
