### ISSUE TITLE
--- Logging error ---

### ISSUE THREAD

**Issue by alexbofa** [Comfy-Org/ComfyUI-Manager#64]
Hello, I have this **Logging error** in console. I do not know what they can interfere with and what it may mean, perhaps the conflict is due to [comfy_mtb](https://github.com/melMass/comfy_mtb/) 
I didn't find any similar errors.

```bat
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 22, in write
    self.file.write(message)
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 391: character maps to <undefined>
Call stack:
  File "E:\ComfyUI\ComfyUI\main.py", line 160, in <module>
    init_custom_nodes()
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1700, in init_custom_nodes
    load_custom_nodes()
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1677, in load_custom_nodes
    success = load_custom_node(module_path, base_node_names)
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 169, in <module>
    log.info(
  File "logging\__init__.py", line 1477, in info
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
```

**Comment by wertos97** [comment]
I'm seeing the same error, it's probably somehow connected to comfy-mtb. However, it doesn't seem to break anything for me so I treat it as a warning message.

**Comment by melMass** [comment]
@ltdrdata I think it's the same issue we had there (i.e encoding in windows):

https://github.com/ltdrdata/ComfyUI-Workflow-Component/pull/9

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager to latest version. And try again.

**Comment by alexbofa** [comment]
> Обновите ComfyUI-Manager до последней версии. И попробуй еще раз.

yes, thank you fixed it and no longer issues these warnings. 🖤
