### ISSUE TITLE
The unsecure feature is disabled, restricting the installation of custom nodes. Please contact the administrator.

### ISSUE THREAD

**Issue by UbuntuJohn** [Comfy-Org/ComfyUI-Manager#672]
Hello,
Whenever I try to install/update a custom node from the manager, I receive the message inside my terminal and the fetch fails.
Tried searching the entire Internet for this error message and couldn't find a single thing.

Special note: I am the administrator.

```
J:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-12 16:41:59.042146
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: J:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: J:\ComfyUI_windows_portable\comfyui.log
Downloading SVD model: svd.safetensors...
'wget' is not recognized as an internal or external command,
operable program or batch file.
Downloading SVD model: svd_image_decoder.safetensors...
'wget' is not recognized as an internal or external command,
operable program or batch file.
Downloading SVD model: svd_xt.safetensors...
'wget' is not recognized as an internal or external command,
operable program or batch file.
Downloading SVD model: svd_xt_image_decoder.safetensors...
'wget' is not recognized as an internal or external command,
operable program or batch file.

Prestartup times for custom nodes:
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.2 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.3 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32693 MB
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
Adding J:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.5.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
### Loading: ComfyUI-Impact-Pack (V5.5.6)
Loaded ImpactPack nodes from J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-main\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-main\brushnet_nodes.py", line 18, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-main\brushnet\brushnet.py", line 10, in <module>
    from diffusers.models.attention_processor import (
ImportError: cannot import name 'ADDED_KV_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\attention_processor.py)

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-main module for custom nodes: cannot import name 'ADDED_KV_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\attention_processor.py)
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070
[Crystools INFO] NVIDIA Driver: 546.33
### Loading: ComfyUI-Impact-Pack (V5.5.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.69.4)
### Loading: ComfyUI-Manager (V2.32.1)
### ComfyUI Revision: 2177 [794a357f] | Released on '2024-05-12'
------------------------------------------
### N-Suite Revision: dbeb9ae9
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.40
Current version of moviepy: 1.0.3
Current version of cv2: 4.7.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.23+cu121
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Current version of timm: 0.9.12
ComfyUI-Portrait-Maker : ### : Check dependencies
ComfyUI-Portrait-Maker : J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\requirements.txt
ComfyUI-Portrait-Maker : aliyun-python-sdk-core-v3==2.13.10

ComfyUI-Portrait-Maker : opencv-python

ComfyUI-Portrait-Maker : tensorflow-cpu

ComfyUI-Portrait-Maker : tensorflow

ComfyUI-Portrait-Maker : onnx

ComfyUI-Portrait-Maker : onnxruntime

ComfyUI-Portrait-Maker : modelscope

ComfyUI-Portrait-Maker : scikit-image

ComfyUI-Portrait-Maker : matplotlib

ComfyUI-Portrait-Maker : insightface

ComfyUI-Portrait-Maker : diffusers==0.18.2

ComfyUI-Portrait-Maker : sentencepiece
2024-05-12 16:42:11,433 - modelscope - INFO - PyTorch version 2.1.0+cu121 Found.
2024-05-12 16:42:11,436 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-05-12 16:42:11,436 - modelscope - INFO - Loading ast index from C:\Users\w3phi\.cache\modelscope\ast_indexer
2024-05-12 16:42:11,530 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 1ce65d02853e12c7910d1cb8638ec8f1 and a total number of 976 components indexed
PyTorch version 2.1.0+cu121 available.
TensorFlow version 2.15.0 available.
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\__init__.py", line 9, in <module>
    from portrait.nodes import *
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\portrait\nodes.py", line 7, in <module>
    from .model_holder import *
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\portrait\model_holder.py", line 1, in <module>
    from modelscope.pipelines import pipeline
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
    from .base import Pipeline
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
    from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\arrow_dataset.py", line 67, in <module>
    from .arrow_reader import ArrowReader
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\arrow_reader.py", line 32, in <module>
    from .download.download_config import DownloadConfig
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\download\__init__.py", line 9, in <module>
    from .download_manager import DownloadManager, DownloadMode
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\download\download_manager.py", line 31, in <module>
    from ..utils import tqdm as hf_tqdm
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\utils\__init__.py", line 18, in <module>
    from .info_utils import VerificationMode
  File "J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\utils\info_utils.py", line 5, in <module>
    from huggingface_hub.utils import insecure_hashlib
ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\__init__.py)

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker module for custom nodes: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (J:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\__init__.py)
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.1.0+cu121
### Loading: Save as Webp
Copying JS files for Workflow loading
[Simswap] - STATUS - Running v0.5.0-a1 in ComfyUI
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\__init__.py", line 14, in <module>
    assert len(svd_checkpoints) > 0, "ERROR: No Stable Video Diffusion checkpoints found. Please download & place them in the ComfyUI/models/svd folder, and restart ComfyUI."
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ERROR: No Stable Video Diffusion checkpoints found. Please download & place them in the ComfyUI/models/svd folder, and restart ComfyUI.

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion module for custom nodes: ERROR: No Stable Video Diffusion checkpoints found. Please download & place them in the ComfyUI/models/svd folder, and restart ComfyUI.
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Ignoring node 'CV2TonemapDurand' due to cv2 edition/version
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
FizzleDorf Custom Nodes: Loaded
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 78 nodes successfuly
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'J:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\CrasHUtils-main\\__init__.py'

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\CrasHUtils-main module for custom nodes: [Errno 2] No such file or directory: 'J:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\CrasHUtils-main\\__init__.py'
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (J:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (J:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it in J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI.
[Power Noise Suite]: 🦚🦚🦚 MooOoo!!! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.

[rgthree] Loaded 38 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Searge-SDXL v4.3.1 in J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes\__init__.py", line 1, in <module>
    import custom_nodes.trNodes.image_layering as image_layering
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes\__init__.py", line 2, in <module>
    import custom_nodes.trNodes.color_correction as color_correction
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes\color_correction.py", line 6, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes module for custom nodes: No module named 'blendmodes'
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "Don't watch the clock; do what it does. Keep going." - Sam Levenson


Import times for custom nodes:
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\gcLatentTunnel.py
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\style_aligned_comfy
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HyperSDXL1StepUnetScheduler
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OtherVAEs
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\CrasHUtils-main
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-RAVE
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-webui-color-enhance
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Saveaswebp
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\CrasHUtils
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyI2I
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-RenderRiftNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes-main
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_dagthomas
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ColorMod
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-video-batches
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.0 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-simswap
   0.3 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MileHighStyler
   0.5 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.6 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.7 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui
   0.9 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.9 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   1.3 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes
   1.4 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker
   1.6 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.9 seconds (IMPORT FAILED): J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-main
   3.5 seconds: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
ERROR: The unsecure feature is disabled, restricting the installation of custom nodes. Please contact the administrator.
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
```

**Comment by jayhsu0627** [comment]
same

**Comment by Autantpourmoi** [comment]
same can't restart

**Comment by UbuntuJohn** [comment]
Found a fix:
Open up config.ini located in custom_nodes/ComfyUI-Manager
Find the line that mentions "disable_unsecure_features" and set it to True from False

disable_unsecure_features = True

Then restart ComfyUI

Not too sure how it became False. I don't think I updated the software in a while.

**Comment by ltdrdata** [comment]
Existing users who have been using version 2.23.2 should have their config.ini set as follows and it should function without issues:
```
disable_unsecure_features = False
```

And one more thing.
Those using version 2.23.1 may experience a temporary issue where the effect of `disable_unsecure_features` works in reverse. Please update manually.

goto `custom_nodes/ComfyUI-Manager` and `git pull`

**Comment by ltdrdata** [comment]
This was my fault. Update to latest version (v2.23.3)
and keep it 
```
disable_unsecure_features = False
```
