### ISSUE TITLE
Node won't import in ComfyUi on Mac

### ISSUE THREAD

**Issue by Aedant13** [Comfy-Org/ComfyUI-Manager#674]
This is the Log I get. Maybe it has to do with my environment being in Python3?

----

```
Restarting... [Legacy Mode]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-12 23:52:31.798069
** Platform: Darwin
** Python version: 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]
** Python executable: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
** Log path: /Users/franck/Documents/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 98304 MB, total RAM 98304 MB
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Adding extra search path checkpoints /Volumes/FrankX9/comfyui/models/Stable-diffusion
Adding extra search path configs /Volumes/FrankX9/comfyui/models/Stable-diffusion
Adding extra search path vae /Volumes/FrankX9/comfyui/models/VAE
Adding extra search path loras /Volumes/FrankX9/comfyui/models/Lora
Adding extra search path loras /Volumes/FrankX9/comfyui/models/LyCORIS
Adding extra search path upscale_models /Volumes/FrankX9/comfyui/models/ESRGAN
Adding extra search path upscale_models /Volumes/FrankX9/comfyui/models/RealESRGAN
Adding extra search path upscale_models /Volumes/FrankX9/comfyui/models/SwinIR
Adding extra search path embeddings /Volumes/FrankX9/comfyui/embeddings
Adding extra search path hypernetworks /Volumes/FrankX9/comfyui/models/hypernetworks
Adding extra search path controlnet /Volumes/FrankX9/comfyui/models/ControlNet
### Loading: ComfyUI-Manager (V2.32.2)
### ComfyUI Revision: 2178 [ece5acb8] | Released on '2024-05-12'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.4.0.dev20240507
No module named 'ultralytics'
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ckpts path: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/ckpts
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using symlinks: False
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /Users/franck/.cache/torch/hub/checkpoints/mobilenet_v2-b0353104.pth

[rgthree] Loaded 38 epic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

_PS_ All packages are installed.
_PS_ backend_path /Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop/Backend.py
Traceback (most recent call last):
  File "/Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop-noplugin.py", line 9, in <module>
    from photoshop import PhotoshopConnection
ModuleNotFoundError: No module named 'photoshop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/franck/Documents/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop/__init__.py", line 68, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop-noplugin.py", line 11, in <module>
    subprocess.run(["python", "-m", "pip", "uninstall", "photoshop"], check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

Cannot import /Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop module for custom nodes: [Errno 2] No such file or directory: 'python'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/franck/Documents/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Python 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> Web extensions folder found at /Users/franck/Documents/ComfyUI/web/extensions/ComfyLiterals
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
[comfy_mtb] | INFO -> loaded 78 nodes successfuly
Traceback (most recent call last):
  File "/Users/franck/Documents/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/franck/Documents/ComfyUI/custom_nodes/insightface/__init__.py'

Cannot import /Users/franck/Documents/ComfyUI/custom_nodes/insightface module for custom nodes: [Errno 2] No such file or directory: '/Users/franck/Documents/ComfyUI/custom_nodes/insightface/__init__.py'

Import times for custom nodes:
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Logic
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds (IMPORT FAILED): /Users/franck/Documents/ComfyUI/custom_nodes/insightface
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI_ExtraModels
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI_InstantID
   0.3 seconds (IMPORT FAILED): /Users/franck/Documents/ComfyUI/custom_nodes/comfyui-photoshop
   0.4 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/comfyui-reactor-node
   0.5 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes
   2.3 seconds: /Users/franck/Documents/ComfyUI/custom_nodes/comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json [DONE]
FETCH DATA from: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]
FETCH DATA from: /Users/franck/Documents/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]


```

**Comment by ltdrdata** [comment]
For installation issues with each node, please contact the repository for each node. You can access the location of each node's repository by clicking on the title in the "install custom node" section.
