### ISSUE TITLE
get_config()['disable_unsecure_features'].lower() == 'True' 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by BlackWyvern** [Comfy-Org/ComfyUI-Manager#675]
Whilst trying to install custom nodes via the manager, I am met with this error.

```FETCH DATA from: I:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
Error handling request
Traceback (most recent call last):
  File "I:\Python\Python3-10-6\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "I:\Python\Python3-10-6\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "I:\Python\Python3-10-6\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "I:\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "I:\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "I:\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 740, in install_custom_node
    if core.is_unsecure_features_disabled():
  File "I:\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 1195, in is_unsecure_features_disabled
    return get_config()['disable_unsecure_features'].lower() == 'True'
AttributeError: 'bool' object has no attribute 'lower'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
```

I am also getting AttributeError: 'bool' object has no attribute 'true' when trying to reset the server.

----

I corrected these issues by changing line 1195 to `return get_config()['disable_unsecure_features'] == True` Removing the typecasting. It's working, but if this breaks something else, I have no clue.

**Comment by aaronhimself** [comment]
same here

**Comment by Amit30swgoh** [comment]
me too 

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/42430868/2fea293e-e38f-4a44-8c01-684ff7c18428)

**Comment by xh31738** [comment]
same

**Comment by xh31738** [comment]
why nobody test？
replace ： ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 1195

def is_unsecure_features_disabled():
return get_config()['disable_unsecure_features'].lower() == 'true'

to：

def is_unsecure_features_disabled():
    return str(get_config().get('disable_unsecure_features', 'False')).lower() == 'true'

final， restart comfyui

**Comment by ltdrdata** [comment]
This is fixed now.
This error occurred in the absence of configuration settings.

**Comment by ltdrdata** [comment]
Update to 2.32.6

**Comment by Amit30swgoh** [comment]
ty Doctor!
