### ISSUE TITLE
issue with updating

### ISSUE THREAD

**Issue by RYG81** [Comfy-Org/ComfyUI-Manager#680]
I am getting this errors in console

Update ComfyUI
ComfyUI update fail: Failed to parse reference information from 'refs/remotes/origin/master'
comfy_path: D:\000AI\ComfyUI\ComfyUI
ERROR: Exception:
Traceback (most recent call last):
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
        ^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
           ^^^^^^^^^^^^^^^^
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid

not sure whats wrong here
can you please help.

**Comment by ltdrdata** [comment]
It seems that your python environment is invalid. 
I reccomend reinstall that.

**Comment by RYG81** [comment]
how to do that without affecting all my node installation and model downloads? is there any easy way? I did use comfyUI update folder batch file that updates everything.

**Comment by ltdrdata** [comment]
> how to do that without affecting all my node installation and model downloads? is there any easy way? I did use comfyUI update folder batch file that updates everything.

First, leave the existing environment as it is, and set up a new environment to test it out.

**Comment by RYG81** [comment]
OK, I will try my best to solve this.
