### ISSUE TITLE
PRESTARTUP FAILED, Windows no venv setup up

### ISSUE THREAD

**Issue by flynet** [Comfy-Org/ComfyUI-Manager#779]
Have this error at start up, please suggest
```
[START] Security scan
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Python11\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "D:\Python11\Lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
        ^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
           ^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python11\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] Неверно задано имя папки
Failed to execute startup-script: G:\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['D:\\Python11\\python.exe', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

Prestartup times for custom nodes:
   1.2 seconds (PRESTARTUP FAILED): G:\ComfyUI\custom_nodes\ComfyUI-Manager

```

**Comment by ltdrdata** [comment]
Why don't you use just portable version of ComfyUI?
Your python environment is invalid.

**Comment by flynet** [comment]
Really, had to re-install python
