### ISSUE TITLE
AttributeError: module 'cm_global' has no attribute 'pip_overrides'

### ISSUE THREAD

**Issue by miniHaLe** [Comfy-Org/ComfyUI-Manager#807]
```
comfy-1  | Error handling request
comfy-1  | Traceback (most recent call last):
comfy-1  |   File "/opt/conda/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
comfy-1  |     resp = await request_handler(request)
comfy-1  |   File "/opt/conda/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
comfy-1  |     resp = await handler(request)
comfy-1  |   File "/opt/conda/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
comfy-1  |     return await handler(request)
comfy-1  |   File "/stable-diffusion/server.py", line 42, in cache_control
comfy-1  |     response: web.Response = await handler(request)
comfy-1  |   File "/stable-diffusion/server.py", line 54, in cors_middleware
comfy-1  |     response = await handler(request)
comfy-1  |   File "/data/config/comfy/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 816, in install_custom_node
comfy-1  |     pkg = core.remap_pip_package(pname)
comfy-1  |   File "/data/config/comfy/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 56, in remap_pip_package
comfy-1  |     if pkg in cm_global.pip_overrides:
comfy-1  | AttributeError: module 'cm_global' has no attribute 'pip_overrides'
```

I have an issue when trying to install some nodes on the comfyUI manager not sure why

**Comment by ltdrdata** [comment]
Make sure your ComfyUI is up to date.

**Comment by Maslino** [comment]
What is ComfyUI-Manager's installation path?

**Comment by bjohnson1701D** [comment]
Just had the same issue on fresh install of ComfyUI, upgrading pip took care of the issue for me.

**Comment by ltdrdata** [comment]
> Just had the same issue on fresh install of ComfyUI, upgrading pip took care of the issue for me.

Show me the full log.
