### ISSUE TITLE
while start the server, the comfyui manager cannot run?

### ISSUE THREAD

**Issue by trouble-maker007** [Comfy-Org/ComfyUI-Manager#819]
```
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/home/work/miniconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/home/work/miniconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/work/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "/home/work/ComfyUI/server.py", line 54, in cors_middleware
    response = await handler(request)
  File "/home/work/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 340, in fetch_customnode_mappings
    mode = request.rel_url.query["mode"]
KeyError: 'mode'
```

**Comment by ltdrdata** [comment]
That is weird. It's impossible error. What is displayed on browser's console log?
