### ISSUE TITLE
The issue has been happening for a few days, how to fix it, thanks

### ISSUE THREAD

**Issue by wip163** [Comfy-Org/ComfyUI-Manager#821]
### ComfyUI Revision: 2288 [f12fa1d8] | Released on '2024-06-26'
Exception in thread Thread-11 (<lambda>):
Traceback (most recent call last):
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 867, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "D:\SDcomfyui\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1694, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "D:\SDcomfyui\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1691, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "D:\SDcomfyui\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1678, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 583, in get_data
    async with session.get(uri) as resp:
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SDcomfyui\ComfyUI_windows\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]

**Comment by ltdrdata** [comment]
Move all custom nodes except ComfyUI-Manager to another directory to remove them, and check if the same issue occurs.

**Comment by wip163** [comment]
Thank you! I followed your method and removed all nodes, but the problem was still not solved.
Thr raw.githubusercontent.com was inaccessible. It is said that this may be due to DNS pollution for some reason.

**Comment by ltdrdata** [comment]
> Thank you! I followed your method and removed all nodes, but the problem was still not solved. Thr raw.githubusercontent.com was inaccessible. It is said that this may be due to DNS pollution for some reason.

If that's the case, you'll have to modify the network configuration.
