### ISSUE TITLE
io.StringIO' object has no attribute 'sync_write "Efficacy Loader"

### ISSUE THREAD

**Issue by ZiBrianQian** [Comfy-Org/ComfyUI-Manager#841]
Not sure what's happening, never had an issue until recently. When trying to use the Efficacy Loader I always get this error now.

!!! Exception during processing!!! 'io.StringIO' object has no attribute 'sync_write'
Traceback (most recent call last):
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 158, in efficientloader
model, clip = load_lora(lora_params, ckpt_name, my_unique_id, cache=lora_cache, ckpt_cache=ckpt_cache, cache_overwrite=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 370, in load_lora
ckpt, clip, _ = load_checkpoint(ckpt_name, id, cache=ckpt_cache)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 246, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 526, in load_checkpoint_guess_config
model = model_config.get_model(sd, diffusion_model_prefix, device=inital_load_device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\comfy\supported_models_base.py", line 60, in get_model
out = model_base.BaseModel(self, model_type=self.model_type(state_dict, prefix), device=device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 87, in init
logging.info("model_type {}".format(model_type.name))
File "logging_init.py", line 2148, in info
File "logging_init_.py", line 1489, in info
File "logging_init_.py", line 1634, in log
File "logging_init.py", line 1644, in handle
File "logging_init_.py", line 1706, in callHandlers
File "logging_init_.py", line 978, in handle
File "C:\SD\comyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 326, in emit
sys.stderr.sync_write(message+'\n', file_only=True)
^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_io.StringIO' object has no attribute 'sync_write'

Can be fixed by restoring to the previos version.

**Comment by ltdrdata** [comment]
This is patched.
