### ISSUE TITLE
ComfyUI startup got stuck after "default cache updated"

### ISSUE THREAD

**Issue by Fanccy315** [Comfy-Org/ComfyUI-Manager#844]
Here are the logs(Terminated ComfyUI using Ctrl+C)

```
** ComfyUI startup time: 2024-07-08 14:32:04.267986
** Platform: Linux
** Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
** Python executable: /home/***/.conda/envs/ComfyUI/bin/python
** ComfyUI Path: /home/***/ComfyUI
** Log path: /home/***/ComfyUI/comfyui.log
Prestartup times for custom nodes:
    1.6 seconds: /home/***/ComfyUI/custom_nodes/ComfyUI-Manager
### Loading: ComfyUI-Manager (V2.46)
### ComfyUI Revision: 2308 [05e83169] | Released on '2024-06-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
```

Sometimes there is an exception thrown

```
** ComfyUI startup time: 2024-07-08 14:41:21.468385
** Platform: Linux
** Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
** Python executable: /home/***/.conda/envs/ComfyUI/bin/python
** ComfyUI Path: /home/***/ComfyUI
** Log path: /home/***/ComfyUI/comfyui.log
Prestartup times for custom nodes:
   0.9 seconds: /home/***/ComfyUI/custom_nodes/ComfyUI-Manager
### Loading: ComfyUI-Manager (V2.46)
### ComfyUI Revision: 2308 [05e83169] | Released on '2024-06-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1694, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/***/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1691, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "/home/***/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1678, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 607, in get_data
    json_obj = json.loads(json_text)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.conda/envs/ComfyUI/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thank you in advance for any help!

**Comment by ltdrdata** [comment]
Based on the symptoms, it seems that downloads are not working properly on your network.

Try downloading the file with 
`wget https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json` and check its contents.

**Comment by Fanccy315** [comment]
Successfully downloaded this file.
I am using reverse proxy to access GitHub,otherwise I cannot access githubusercontent.

```
--2024-07-08 16:05:32--  https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
已载入 CA 证书“/etc/ssl/certs/ca-certificates.crt”
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 127.0.0.1
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|127.0.0.1|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：475544 (464K) [text/plain]
正在保存至: “extension-node-map.json”

extension-node-map 100%[================>] 464.40K  1.16MB/s  用时 0.4s    

2024-07-08 16:05:33 (1.16 MB/s) - 已保存 “extension-node-map.json” [475544/475544])
```

**Comment by ltdrdata** [comment]
> Successfully downloaded this file. I am using reverse proxy to access GitHub,otherwise I cannot access githubusercontent.
> 
> ```
> --2024-07-08 16:05:32--  https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> 已载入 CA 证书“/etc/ssl/certs/ca-certificates.crt”
> 正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 127.0.0.1
> 正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|127.0.0.1|:443... 已连接。
> 已发出 HTTP 请求，正在等待回应... 200 OK
> 长度：475544 (464K) [text/plain]
> 正在保存至: “extension-node-map.json”
> 
> extension-node-map 100%[================>] 464.40K  1.16MB/s  用时 0.4s    
> 
> 2024-07-08 16:05:33 (1.16 MB/s) - 已保存 “extension-node-map.json” [475544/475544])
> ```

This PR will be merged later.
https://github.com/ltdrdata/ComfyUI-Manager/pull/795

**Comment by megapin-bit** [comment]
Hello, does anyone understand, are these default cache update links a problem? periodically before the start of generation, a reconnection occurs
![Uploading Screenshot_20240927-213342.png…]()

**Comment by ltdrdata** [comment]
This is implemented.

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#environment-variables
