### ISSUE TITLE
Question about pip install

### ISSUE THREAD

**Issue by za-wa-n-go** [Comfy-Org/ComfyUI-Manager#878]
When installing Python packages with StabilityMatrix, it fails, but it succeeds when using ComfyUI-Manager. Do you know why?

**Comment by ltdrdata** [comment]
This question cannot be answered because there is insufficient information.

**Comment by za-wa-n-go** [comment]
I don't think it will be resolved, but if you know the reason, I'd like to know.
When I try to install StabilityMatrix with pip, I get the following error.
The installation completes without errors in ComfyUI_Manager.

```
Collecting pixeloe
  Using cached pixeloe-0.0.10.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\aiart\Data\Packages\ComfyUI\venv\lib\site-packages\setuptools\__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "C:\aiart\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "C:\aiart\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 91, in do_override
          ensure_local_distutils()
        File "C:\aiart\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 78, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: C:\aiart\Data\Packages\ComfyUI\venv\Scripts\python310.zip\distutils\core.pyc
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process python failed with exit-code 1.
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Models.PackageModification.PipStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PipStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by za-wa-n-go** [comment]
It occurs with a specific package and continues to occur once it happens.
Since it does not occur from the ComfyUI_Manager side, I believe that some kind of ingenuity in package installation by the Manager is influencing it.

**Comment by ltdrdata** [comment]
> It occurs with a specific package and continues to occur once it happens. Since it does not occur from the ComfyUI_Manager side, I believe that some kind of ingenuity in package installation by the Manager is influencing it.

The Python environment configured with StabilityMatrix appears to be different from a Python environment not using StabilityMatrix.
