### ISSUE TITLE
安装后控制台就成这样了

### ISSUE THREAD

**Issue by plasx520** [Comfy-Org/ComfyUI-Manager#896]
`Exception in thread Thread-6 (<lambda>):
Traceback (most recent call last):
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 72, in run
  File "<enhanced_experience vendors.sentry_sdk._compat>", line 115, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 70, in run
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ceshi\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1697, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\ceshi\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1694, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "D:\ceshi\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1681, in get_cache
    json_obj = await core.get_data(uri, True)
  File "D:\ceshi\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 600, in get_data
    async with session.get(uri) as resp:
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\ceshi\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.`

**Comment by ltdrdata** [comment]
It seesm that you are experiencing network issue.
It is recommended to use a VPN.

**Comment by akfheaven** [comment]
same, how to disable it auto fetch, is it neccesery for startup

**Comment by akfheaven** [comment]
same, is it necessary for every startup? how can i disable it

**Comment by akfheaven** [comment]
same, is it necessary for every startup? can i disable it and fetch when I need it
