### ISSUE TITLE
Unable to open link due to incorrect connection address

### ISSUE THREAD

**Issue by chioulin** [Comfy-Org/ComfyUI-Manager#91]
Unable to open link due to incorrect connection address: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/node_db/new/custom-node-list.json

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/node_db/new/custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1091, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
  File "asyncio\base_events.py", line 1247, in start_tls
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 502, in fetch_customnode_list
    json_obj = await get_data(uri)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 326, in get_data
    async with session.get(uri) as resp:
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1328, in _create_proxy_connection
    return await self._start_tls_connection(
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1111, in _start_tls_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [None]

**Comment by ltdrdata** [comment]
> 

Can you open this page on browser?

https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/node_db/new/custom-node-list.json

**Comment by chioulin** [comment]
> 
Cannot connect to host

**Comment by ltdrdata** [comment]
> > 
> 
> Cannot connect to host

The issue is with your network, so you're unable to access GitHub properly. In this case, the only option is to use `use local db`, but you're concerned whether `git clone` will work correctly.

**Comment by chioulin** [comment]
> > > 
> > 
> > 
> > 无法连接到主机
> 
> 问题出在您的网络上，因此您无法正常访问 GitHub。在这种情况下，唯一的选择是使用`use local db`，但您担心是否`git clone`可以正常工作。

Thank you for your reply, can update, used VPN, git clone no problem!

**Comment by chioulin** [comment]
> 

How should use local db be used?

**Comment by chioulin** [comment]
> > > 
> > 
> > 
> > Cannot connect to host
> 
> The issue is with your network, so you're unable to access GitHub properly. In this case, the only option is to use `use local db`, but you're concerned whether `git clone` will work correctly.

CMD has a code but can't open that link https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by ltdrdata** [comment]
> > > > 
> > > 
> > > 
> > > Cannot connect to host
> > 
> > 
> > The issue is with your network, so you're unable to access GitHub properly. In this case, the only option is to use `use local db`, but you're concerned whether `git clone` will work correctly.
> 
> CMD has a code but can't open that link https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

It appears that access to some resources on GitHub from your network is being blocked by something. There's no way around this. If you have no issues with functions like `git clone`, I recommend periodically updating ComfyUI-Manager while using the local database.

**Comment by ltdrdata** [comment]
This patch will resolve this issue.
https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960
