### ISSUE TITLE
Utter mess after installing following instructions

### ISSUE THREAD

**Issue by Nitrowing** [Comfy-Org/ComfyUI-Manager#978]
I basically got a whole new ComfyUI embedded in the E:\StableSwarmUI-master\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager folder and now my run_nvidia_gpu.bat throws a list of errors and quits

E:\StableSwarmUI-master\dlbackend\comfy>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 980, in exec_module
  File "<frozen site>", line 626, in <module>
  File "<frozen site>", line 613, in main
  File "<frozen site>", line 394, in addsitepackages
  File "<frozen site>", line 236, in addsitedir
  File "<frozen site>", line 188, in addpackage
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 983: character maps to <undefined>

E:\StableSwarmUI-master\dlbackend\comfy>pause
Press any key to continue . . .

**Comment by ltdrdata** [comment]
It seems your ComfyUI custom node installation is incorrect.
Delete all subdirectories in `ComfyUI/custom_nodes` and restart.
If there are no errors, check the install guide in the repo and install in order.
