### ISSUE TITLE
[bug] Manager causes the new ComfyUI front end search to break

### ISSUE THREAD

**Issue by gonzalu** [Comfy-Org/ComfyUI-Manager#992]
Hello,

I have this problem with the new front end that double-click to search for nodes is not working when the ComfyUI manager is installed. 

When I disable ALL custom nodes, the feature works fine.
When I disable ALL custom nodes EXCEPT the manager, the problem is there

Thank you.

![image](https://github.com/user-attachments/assets/c8d265ea-5028-429c-a43f-3109d0e2b644)

**Comment by ltdrdata** [comment]
Show me the browser console log. (press F12 if chrome)

**Comment by gonzalu** [comment]
Further troubleshooting shows that ANY custom node causes it. Only way I get it to work is if ALL custom nodes are not enabled :( 

```
index.html:4 ComfyUI Front-end version: 1.2.30
:8188/api/userdata/workflows%2F.index.json:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
logging.ts:331  Error loading extension /extensions/Primere/vendor/LoadImage/load-image-scale.js TypeError: Cannot read properties of undefined (reading 'transform')
    at load-image-scale.js:28:37
    at load-image-scale.js:23:5
    at load-image-scale.js:25:3
console.<computed> @ logging.ts:331
:8188/extensions/dzNodes/dz_DZ_widgets.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
logging.ts:331  Error loading extension /extensions/dzNodes/dz_debug.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js
console.<computed> @ logging.ts:331
:8188/api/DZ/debug:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
logging.ts:331  Error calling extension 'DZ.widgets' method 'init' Object Object Object
console.<computed> @ logging.ts:331
logging.ts:331  Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": -1, "ram_total": 68658769920, "ram_used": 13356285952, "ram_used_percent": 19.5, "hdd_total": -1, "hdd_used": -1, "hdd_used_percent": -1, "device_type": "cuda", "gpus": [{"gpu_utilization": 5, "gpu_temperature": 0, "vram_total": 0, "vram_used": 0, "vram_used_percent": 0}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.ts:226:23)
console.<computed> @ logging.ts:331
logging.ts:331 Empty components: policy ignored
logging.ts:331 [🐍 pysssss] Skipping LinkRenderMode as core extension found
:8188/api/userdata/workflows%2F.index.json:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/DZ/debug:1 
        
        
        Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/pysssss/autocomplete:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'split')
    at getNodeSource (nodeSource.ts:9:33)
    at _NodeSourceFilter.getNodeOptions (nodeSearchService.ts:99:13)
    at nodeSearchService.ts:51:35
    at Array.reduce (<anonymous>)
    at _NodeSourceFilter.getAllNodeOptions (nodeSearchService.ts:50:18)
    at new NodeFilter (nodeSearchService.ts:44:43)
    at new NodeSourceFilter (nodeSearchService.ts:92:8)
    at new NodeSearchService (nodeSearchService.ts:140:29)
    at Proxy.nodeSearchService (nodeDefStore.ts:273:14)
    at pinia.mjs:1233:38
console.<computed> @ logging.ts:331
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at Proxy.onFocus (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331  'execution_start' fired before prompt was made.
console.<computed> @ logging.ts:331
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 Show mode: Normal
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'nodeFilters')
    at NodeSearchFilter.vue:53:37
    at runtime-core.esm-bundler.js:1808:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1788:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:379:35)
    at flushJobs (runtime-core.esm-bundler.js:415:5)
    at flushJobs (runtime-core.esm-bundler.js:419:7)
console.<computed> @ logging.ts:331
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at Proxy.onFocus (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
console.<computed> @ logging.ts:331
logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331  SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331  'execution_start' fired before prompt was made.
console.<computed> @ logging.ts:331
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
2logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
127.0.0.1/:1 Autofocus processing was blocked because a document already has a focused element.
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'nodeFilters')
    at NodeSearchFilter.vue:53:37
    at runtime-core.esm-bundler.js:1808:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1788:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:379:35)
    at flushJobs (runtime-core.esm-bundler.js:415:5)
    at flushJobs (runtime-core.esm-bundler.js:419:7)
console.<computed> @ logging.ts:331
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at Proxy.onFocus (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331  'execution_start' fired before prompt was made.
console.<computed> @ logging.ts:331
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  SyntaxError: Unexpected token '.', "." is not valid JSON
    at JSON.parse (<anonymous>)
    at _ComfyApp.<anonymous> (app.ts:1134:27)
    at Generator.next (<anonymous>)
    at index-CaD4RONs.js:68:62
    at new Promise (<anonymous>)
    at __async (index-CaD4RONs.js:52:10)
    at HTMLDocument.<anonymous> (app.ts:1086:69)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
100logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
100logging.ts:331 node_in_loop made NaN checks
logging.ts:331 [NestedNodeBuilder] unnestedToNestedIds: Object
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'nodeFilters')
    at NodeSearchFilter.vue:53:37
    at runtime-core.esm-bundler.js:1808:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1788:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:379:35)
    at flushJobs (runtime-core.esm-bundler.js:415:5)
    at flushJobs (runtime-core.esm-bundler.js:419:7)
console.<computed> @ logging.ts:331
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at Proxy.onFocus (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
console.<computed> @ logging.ts:331
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        
          
          
          Don't show again
        
        
```

**Comment by gonzalu** [comment]
Now it started working all of a sudden!! 

WHAT?? This is so weird :( I have updated nothing... 

![image](https://github.com/user-attachments/assets/756dd0b2-7229-428e-b09d-f9403e785014)

**Comment by ltdrdata** [comment]
You have to remove `NestedNodeBuilder`.
It should be removed long time ago since GroupNode feature is added.

**Comment by gonzalu** [comment]
Thank you... maybe when I cleaned up some nodes it got dumped. I did re-install the manager, but it did not fix itself immediately. I am just glad it is working :D 
Thank you!

**Comment by gonzalu** [comment]
Looks like NestedNodeBuilder was dirty and did not get picked up by the manager and I missed it MANUALLY... so after going in by hand, I deleted it for good. 

Thanks as always!!

**Comment by ltdrdata** [comment]
That node is moved to legacy channel. So you cannot see in the default channel list.
